package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: a9a  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class a9a implements aj4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new nz8("string:channel_tts_description", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11675L, 115L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9883L, 87L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10375L, 115L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14567L, 155L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9628L, 95L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10175L, 107L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10587L, 111L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 15739L, 163L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9435L, 99L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10083L, 103L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10507L, 83L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9991L, 71L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10075L, 103L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9983L, 99L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10111L, 107L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13499L, 131L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15479L, 179L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9627L, 87L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13547L, 127L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8555L, 87L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8475L, 83L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11058L, 119L)}));
    }

    private final Object b() {
        return new nz8("string:close", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12304L, 29L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10412L, 25L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10928L, 29L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15352L, 37L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10379L, 21L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10728L, 21L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11208L, 21L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16552L, 45L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9936L, 21L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10648L, 21L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11096L, 25L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10516L, 21L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10668L, 25L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10528L, 25L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10652L, 21L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14216L, 33L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16288L, 25L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10132L, 21L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14292L, 33L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9024L, 21L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8940L, 21L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11929L, 21L)}));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new nz8("string:year", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 57609L, 20L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 47265L, 16L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 49521L, 20L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 71469L, 24L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51993L, 20L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 48813L, 20L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 50521L, 16L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 75457L, 28L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 45269L, 20L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 47821L, 20L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 50081L, 16L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 48337L, 16L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 47473L, 20L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 47745L, 16L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 48409L, 16L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 65669L, 20L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 75153L, 20L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 46689L, 20L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 65621L, 20L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 40505L, 16L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 40257L, 16L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 73318L, 20L)}));
            case 1:
                return new nz8("string:yesterday", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 57630L, 25L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 47282L, 25L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 49542L, 29L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 71494L, 29L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 52014L, 29L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 48834L, 25L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 50538L, 25L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 75486L, 25L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 45290L, 29L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 47842L, 25L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 50098L, 25L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 48354L, 25L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 47494L, 29L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 47762L, 29L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 48426L, 25L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 65690L, 33L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 75174L, 49L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 46710L, 25L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 65642L, 33L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 40522L, 25L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 40274L, 25L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 73339L, 29L)}));
            case 2:
                return new nz8("string:video_setting_seconds", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50992L, 37L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72091L, 45L)}));
            case 3:
                return new nz8("string:video_setting_mute", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50693L, 34L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71663L, 46L)}));
            case 4:
                return new nz8("string:video_setting_pip", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50728L, 49L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71710L, 57L)}));
            case 5:
                return new nz8("string:video_setting_playback", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50778L, 42L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71829L, 46L)}));
            case 6:
                return new nz8("string:video_setting_playback_speed", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71768L, 60L)));
            case 7:
                return new nz8("string:video_setting_resize_fill", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50821L, 41L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71876L, 49L)}));
            case 8:
                return new nz8("string:video_setting_resize_fit", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50863L, 36L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71926L, 56L)}));
            case 9:
                return new nz8("string:video_setting_resize_mode", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 50900L, 49L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 71983L, 61L)}));
            case 10:
                return new nz8("string:video_setting_seek_backward", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51030L, 55L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72137L, 47L)}));
            case 11:
                return new nz8("string:video_setting_seek_forward", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51086L, 50L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72185L, 46L)}));
            case 12:
                return new nz8("string:video_setting_show_subtitle", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51137L, 55L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72232L, 67L)}));
            case 13:
                return new nz8("string:video_setting_speed_value", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72300L, 41L)));
            case 14:
                return new nz8("string:video_setting_subtitle", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51743L, 42L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 73013L, 46L)}));
            case 15:
                return new nz8("string:video_setting_subtitle_background_color", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 56924L, 75L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 46668L, 67L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 48940L, 71L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 70692L, 79L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51193L, 71L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 48200L, 67L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 49936L, 67L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 74612L, 99L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 44700L, 63L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 47220L, 67L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 49516L, 59L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 47736L, 63L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 46884L, 71L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 47144L, 63L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 47800L, 63L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 64948L, 71L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 74360L, 87L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 46088L, 67L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 64876L, 71L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 39968L, 63L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 39720L, 63L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72342L, 63L)}));
            case 16:
                return new nz8("string:video_setting_subtitle_background_opacity", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 51265L, 85L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 72406L, 89L)}));
            case 17:
                return new nz8("string:browser_history", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 10987L, 51L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9287L, 55L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 9747L, 43L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 13731L, 75L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9056L, 47L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9547L, 55L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 9903L, 55L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 14843L, 91L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 8907L, 51L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9471L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 9879L, 39L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9443L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9491L, 47L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9371L, 55L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9467L, 59L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 12731L, 67L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 14495L, 87L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9063L, 47L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 12695L, 67L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8083L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8007L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10398L, 55L)}));
            case 18:
                return new nz8("string:check_new_chapter_success", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12108L, 73L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10220L, 81L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10748L, 69L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15100L, 97L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10137L, 73L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10544L, 69L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11000L, 77L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16280L, 93L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9784L, 57L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10464L, 73L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10876L, 101L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10332L, 81L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10476L, 77L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10356L, 65L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10468L, 69L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13968L, 89L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16044L, 81L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9960L, 65L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14044L, 81L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8872L, 65L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8788L, 65L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11683L, 65L)}));
            case 19:
                return new nz8("string:cancel", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11039L, 30L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9343L, 26L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 9791L, 26L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 13807L, 34L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9104L, 22L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9603L, 26L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 9959L, 26L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 14935L, 50L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 8959L, 22L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9527L, 26L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 9919L, 34L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9487L, 22L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9539L, 26L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9427L, 22L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9527L, 26L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 12799L, 30L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 14583L, 38L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9111L, 22L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 12763L, 38L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8123L, 22L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8047L, 22L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10454L, 22L)}));
            case 20:
                return new nz8("string:check_new_episode_success", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10261L, 73L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11811L, 61L)}));
            case 21:
                return new nz8("string:choose_category", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12252L, 51L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10364L, 47L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10876L, 51L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15280L, 71L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10335L, 43L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10676L, 51L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11148L, 59L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16460L, 91L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9892L, 43L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10596L, 51L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11044L, 51L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10464L, 51L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10616L, 51L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10480L, 47L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10600L, 51L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14140L, 75L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16204L, 83L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10088L, 43L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14212L, 79L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8984L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8900L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11873L, 55L)}));
            case 22:
                return b();
            case 23:
                return new nz8("string:cloud_sync_auto_on_change", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12090L, 77L)));
            case 24:
                return new nz8("string:cloud_sync_auto_on_change_desc", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11951L, 138L)));
            case 25:
                return new nz8("string:cloud_sync_auto_on_open", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12281L, 79L)));
            case 26:
                return new nz8("string:cloud_sync_auto_on_open_desc", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12168L, 112L)));
            case 27:
                return new nz8("string:cloud_sync_conflict_ask", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12361L, 59L)));
            case 28:
                return a();
            default:
                return new nz8("string:cloud_sync_conflict_auto", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 12421L, 56L)));
        }
    }
}
