package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: e9a  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class e9a implements aj4 {
    public final /* synthetic */ int a;

    private final Object a() {
        return new nz8("string:check_new_chapter_failed", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11979L, 128L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10123L, 96L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10639L, 108L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14935L, 164L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10040L, 96L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10443L, 100L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10871L, 128L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16131L, 148L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9695L, 88L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10339L, 124L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10755L, 120L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10231L, 100L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10347L, 128L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10243L, 112L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10371L, 96L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13831L, 136L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15891L, 152L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9867L, 92L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13887L, 156L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8795L, 76L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8711L, 76L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11582L, 100L)}));
    }

    private final Object b() {
        return new nz8("string:community_delete_post_title", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10626L, 51L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18016L, 59L)}));
    }

    private final Object e() {
        return new nz8("string:community_deleted_post", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10678L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18076L, 66L)}));
    }

    private final Object i() {
        return new nz8("string:community_global_chat", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12430L, 57L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10526L, 45L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 11038L, 53L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15514L, 73L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10758L, 45L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10846L, 45L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11322L, 49L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16714L, 73L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10042L, 41L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10758L, 49L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11214L, 53L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10622L, 49L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10774L, 49L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10638L, 45L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10762L, 45L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14366L, 53L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16438L, 65L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10230L, 45L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14442L, 65L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9118L, 45L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 9042L, 45L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18176L, 45L)}));
    }

    private final Object k() {
        return new nz8("string:community_group_add_member", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18222L, 58L)));
    }

    private final Object l() {
        return new nz8("string:channel_download_title", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11616L, 58L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9828L, 54L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10316L, 58L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14500L, 66L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9573L, 54L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10116L, 58L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10516L, 70L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 15656L, 82L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9388L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10028L, 54L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10440L, 66L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9932L, 58L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10024L, 50L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9928L, 54L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10048L, 62L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13432L, 66L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15392L, 86L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9580L, 46L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13468L, 78L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8508L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8428L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11007L, 50L)}));
    }

    private final Object m() {
        return new nz8("string:community_group_change_cover", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18281L, 60L)));
    }

    private final Object n() {
        return new nz8("string:community_group_public_list_empty", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 19699L, 77L)));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new nz8("string:cloud_sync_title", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 16991L, 48L)));
            case 1:
                return new nz8("string:channel_complete_title", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11428L, 66L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9664L, 62L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10124L, 62L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14260L, 74L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9413L, 54L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9940L, 58L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10320L, 66L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 15400L, 82L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9240L, 50L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9848L, 58L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10260L, 62L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9772L, 58L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9868L, 54L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9752L, 62L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9864L, 58L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13204L, 78L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15080L, 102L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9432L, 58L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13216L, 90L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8380L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8300L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10827L, 66L)}));
            case 2:
                return new nz8("string:cloud_sync_wifi_only", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17154L, 64L)));
            case 3:
                return new nz8("string:cloud_sync_wifi_only_desc", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17040L, 113L)));
            case 4:
                return new nz8("string:chat_image", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11944L, 34L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10088L, 34L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10612L, 26L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14896L, 38L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10009L, 30L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10412L, 30L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10840L, 30L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16088L, 42L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9664L, 30L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10304L, 34L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10724L, 30L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10196L, 34L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10312L, 34L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10212L, 30L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10340L, 30L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13780L, 50L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15844L, 46L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9836L, 30L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13836L, 50L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8764L, 30L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8680L, 30L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11543L, 38L)}));
            case 5:
                return new nz8("string:color", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12376L, 21L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10472L, 21L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10988L, 21L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15452L, 29L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10431L, 21L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10792L, 21L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11264L, 25L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16644L, 25L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9992L, 21L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10708L, 21L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11164L, 17L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10576L, 21L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10724L, 21L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10588L, 21L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10712L, 17L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14292L, 25L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16356L, 21L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10184L, 21L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14372L, 29L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9072L, 21L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8996L, 21L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17249L, 21L)}));
            case 6:
                return new nz8("string:color_hex", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12334L, 41L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10438L, 33L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10958L, 29L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15390L, 61L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10401L, 29L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10750L, 41L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11230L, 33L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16598L, 45L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9958L, 33L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10670L, 37L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11122L, 41L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10538L, 37L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10694L, 29L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10554L, 33L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10674L, 37L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14250L, 41L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16314L, 41L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10154L, 29L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14326L, 45L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9046L, 25L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8962L, 33L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17219L, 29L)}));
            case 7:
                return new nz8("string:comment", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12398L, 31L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10494L, 31L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 11010L, 27L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15482L, 31L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10453L, 27L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10814L, 31L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11290L, 31L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16670L, 43L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10014L, 27L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10730L, 27L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11182L, 31L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10598L, 23L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10746L, 27L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10610L, 27L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10730L, 31L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14318L, 47L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16378L, 59L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10206L, 23L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14402L, 39L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9094L, 23L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 9018L, 23L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17271L, 31L)}));
            case 8:
                return new nz8("string:community", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12556L, 37L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10632L, 29L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 11160L, 29L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15664L, 41L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 11717L, 29L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10952L, 29L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11428L, 33L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16880L, 41L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10136L, 29L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10864L, 29L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 11328L, 41L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10728L, 33L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10884L, 29L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10740L, 37L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10868L, 33L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14500L, 45L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16588L, 37L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10344L, 29L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14580L, 41L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 9216L, 25L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 9140L, 25L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 21701L, 37L)}));
            case 9:
                return new nz8("string:community_add_conversation", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17303L, 70L)));
            case 10:
                return new nz8("string:community_chat_placeholder", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10481L, 50L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17374L, 54L)}));
            case 11:
                return new nz8("string:community_conversation_empty", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17578L, 84L)));
            case 12:
                return new nz8("string:community_conversation_empty_description", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17429L, 148L)));
            case 13:
                return new nz8("string:channel_download_description", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 11495L, 120L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 9727L, 100L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10187L, 128L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 14335L, 164L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 9468L, 104L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 9999L, 116L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10387L, 128L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 15483L, 172L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9291L, 96L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 9907L, 120L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10323L, 116L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 9831L, 100L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 9923L, 100L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 9815L, 112L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 9923L, 124L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 13283L, 148L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 15183L, 208L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 9491L, 88L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 13307L, 160L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8427L, 80L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8347L, 80L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10894L, 112L)}));
            case 14:
                return new nz8("string:community_conversation_group", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17663L, 44L)));
            case 15:
                return new nz8("string:check_new_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 12182L, 69L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10302L, 61L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10818L, 57L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 15198L, 81L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10211L, 49L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10614L, 61L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 11078L, 69L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 16374L, 85L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 9842L, 49L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10538L, 57L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10978L, 65L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10414L, 49L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10554L, 61L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10422L, 57L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10538L, 61L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 14058L, 81L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 16126L, 77L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10026L, 61L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 14126L, 85L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 8938L, 45L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 8854L, 45L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 11749L, 61L)}));
            case 16:
                return new nz8("string:community_conversation_list", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17708L, 63L)));
            case 17:
                return new nz8("string:community_conversation_search", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17772L, 73L)));
            case 18:
                return new nz8("string:community_create_group_chat", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17846L, 59L)));
            case 19:
                return new nz8("string:community_delete", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10725L, 32L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18143L, 32L)}));
            case 20:
                return new nz8("string:community_delete_post_message", cz.t0(new a09[]{new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10532L, 93L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 17906L, 109L)}));
            case 21:
                return b();
            case 22:
                return e();
            case 23:
                return i();
            case 24:
                return k();
            case 25:
                return l();
            case 26:
                return a();
            case 27:
                return m();
            case 28:
                return n();
            default:
                return new nz8("string:community_group_cover_optional", icd.r(new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 18342L, 78L)));
        }
    }
}
