package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: eaa  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class eaa implements aj4 {
    public final /* synthetic */ int a;

    private final Object A() {
        return new nz8("string:start_checking_new_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47242L, 106L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38750L, 90L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40586L, 86L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58846L, 110L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40764L, 82L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 40014L, 98L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41574L, 102L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62114L, 114L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37270L, 70L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39202L, 78L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41454L, 106L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39802L, 86L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 39034L, 94L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39110L, 94L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39650L, 94L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 54054L, 102L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61610L, 106L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38230L, 94L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 54066L, 122L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33290L, 66L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33078L, 66L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 59620L, 86L)}));
    }

    private final Object a() {
        return new nz8("string:setting_restore_mode_merge_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41030L, 163L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33962L, 103L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35582L, 123L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51426L, 215L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 36192L, 91L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34898L, 123L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36306L, 127L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54558L, 223L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32654L, 95L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34290L, 107L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36206L, 127L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34858L, 119L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34118L, 115L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34194L, 95L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34666L, 119L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47298L, 191L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54142L, 183L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33350L, 111L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47382L, 167L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29130L, 87L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28946L, 87L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 53126L, 103L)}));
    }

    private final Object b() {
        return new nz8("string:shelf_add_not_view", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45103L, 50L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36983L, 42L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38835L, 46L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56355L, 62L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39173L, 42L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38207L, 38L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39807L, 34L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59395L, 74L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35695L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37487L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39619L, 38L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38071L, 38L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37323L, 42L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37343L, 42L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37907L, 42L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51623L, 62L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59131L, 58L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36563L, 50L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51619L, 62L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31847L, 38L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31679L, 38L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57841L, 38L)}));
    }

    private final Object e() {
        return new nz8("string:shelf_column", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45154L, 36L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37026L, 32L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38882L, 36L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56418L, 40L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39216L, 28L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38246L, 32L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39842L, 28L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59470L, 36L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35742L, 28L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37538L, 36L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39658L, 32L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38110L, 28L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37366L, 32L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37386L, 32L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37950L, 32L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51686L, 36L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59190L, 36L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36614L, 28L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51682L, 36L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31886L, 28L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31718L, 28L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57880L, 40L)}));
    }

    private final Object i() {
        return new nz8("string:shelf_last_add", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45191L, 66L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37059L, 50L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38919L, 54L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56459L, 74L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39245L, 42L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38279L, 54L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39871L, 42L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59507L, 82L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35771L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37575L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39691L, 38L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38139L, 42L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37399L, 46L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37419L, 42L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37983L, 54L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51723L, 74L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59227L, 66L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36643L, 38L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51719L, 66L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31915L, 38L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31747L, 38L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57921L, 38L)}));
    }

    private final Object k() {
        return new nz8("string:shelf_last_read", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45258L, 51L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37110L, 51L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38974L, 51L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56534L, 75L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39288L, 43L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38334L, 51L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39914L, 43L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59590L, 79L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35818L, 51L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37626L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39730L, 39L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38182L, 47L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37446L, 43L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37462L, 47L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38038L, 51L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51798L, 79L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59294L, 55L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36682L, 51L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51786L, 79L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31954L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31786L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57960L, 43L)}));
    }

    private final Object l() {
        return new nz8("string:shelf_last_update", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45310L, 65L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37162L, 57L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39026L, 53L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56610L, 77L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39332L, 49L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38386L, 61L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39958L, 57L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59670L, 73L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35870L, 45L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37682L, 53L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39770L, 41L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38230L, 53L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37490L, 49L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37510L, 57L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38090L, 57L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51878L, 77L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59350L, 73L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36734L, 49L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51866L, 73L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31994L, 41L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31826L, 41L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58004L, 49L)}));
    }

    private final Object m() {
        return new nz8("string:setting_reader_turn_page_anim", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40237L, 85L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33301L, 73L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 34989L, 69L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50521L, 85L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 35507L, 65L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34285L, 73L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35665L, 73L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53465L, 113L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32037L, 69L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33729L, 65L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35605L, 85L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34305L, 69L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33529L, 65L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33597L, 69L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34041L, 81L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46385L, 93L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53053L, 113L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32725L, 65L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46461L, 109L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28673L, 53L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28489L, 53L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 52293L, 81L)}));
    }

    private final Object n() {
        return new nz8("string:shelf_often_read", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45376L, 60L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37220L, 52L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39080L, 52L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56688L, 72L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39382L, 48L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38448L, 52L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40016L, 48L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59744L, 76L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35916L, 44L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37736L, 52L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39812L, 40L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38284L, 48L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37540L, 40L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37568L, 48L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38148L, 56L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51956L, 80L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59424L, 48L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36784L, 52L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51940L, 76L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32036L, 40L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31868L, 40L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58054L, 52L)}));
    }

    private final Object o() {
        return new nz8("string:setting_restore_mode_missing", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41435L, 108L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34235L, 72L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35903L, 84L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51931L, 104L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 36445L, 64L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35199L, 68L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36651L, 96L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 55059L, 120L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32931L, 72L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34575L, 68L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36527L, 64L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 35187L, 72L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34431L, 88L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34451L, 72L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34971L, 76L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47755L, 124L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54623L, 120L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33647L, 80L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47783L, 96L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29371L, 64L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29187L, 64L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 53439L, 80L)}));
    }

    private final Object p() {
        return new nz8("string:shelf_show", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45649L, 26L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37457L, 30L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39289L, 30L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56977L, 42L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39587L, 26L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38677L, 30L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40253L, 30L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60089L, 42L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36105L, 30L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37973L, 26L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40025L, 26L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38493L, 26L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37769L, 30L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37813L, 26L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38381L, 26L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52229L, 46L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59741L, 34L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37005L, 30L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52289L, 46L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32221L, 26L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32053L, 26L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58287L, 34L)}));
    }

    private final Object q() {
        return new nz8("string:shelf_show_new_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45437L, 78L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37273L, 62L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39133L, 46L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56761L, 62L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39431L, 46L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38501L, 54L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40065L, 54L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59821L, 106L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35961L, 50L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37789L, 58L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39853L, 62L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38333L, 50L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37581L, 66L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37617L, 66L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38205L, 54L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52037L, 58L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59473L, 74L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36837L, 58L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52017L, 94L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32077L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31909L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58107L, 58L)}));
    }

    private final Object r() {
        return new nz8("string:shelf_show_read_percent", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45516L, 63L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37336L, 55L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39180L, 51L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56824L, 75L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39478L, 55L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38556L, 59L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40120L, 63L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59928L, 87L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36012L, 47L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37848L, 59L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39916L, 47L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38384L, 55L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37648L, 51L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37684L, 55L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38260L, 59L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52096L, 71L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59548L, 103L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36896L, 55L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52112L, 71L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32124L, 47L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31956L, 47L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58166L, 59L)}));
    }

    private final Object s() {
        return new nz8("string:shelf_show_total_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45580L, 68L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37392L, 64L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39232L, 56L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56900L, 76L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39534L, 52L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38616L, 60L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40184L, 68L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60016L, 72L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36060L, 44L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37908L, 64L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39964L, 60L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38440L, 52L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37700L, 68L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37740L, 72L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38320L, 60L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52168L, 60L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59652L, 88L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36952L, 52L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52184L, 104L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32172L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32004L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58226L, 60L)}));
    }

    private final Object t() {
        return new nz8("string:shelf_sort_by", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45676L, 45L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37488L, 37L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39320L, 41L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57020L, 49L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39614L, 33L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38708L, 37L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40284L, 33L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60132L, 73L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36136L, 33L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38000L, 37L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40052L, 37L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38520L, 29L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37800L, 37L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37840L, 41L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38408L, 37L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52276L, 57L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59776L, 53L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37036L, 33L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52336L, 53L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32248L, 29L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32080L, 29L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58322L, 37L)}));
    }

    private final Object u() {
        return new nz8("string:shelf_sort_order", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45722L, 44L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37526L, 36L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39362L, 40L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57070L, 40L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39648L, 32L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38746L, 32L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40318L, 32L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60206L, 40L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36170L, 32L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38038L, 32L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40090L, 32L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38550L, 32L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37838L, 36L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37882L, 40L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38446L, 32L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52334L, 44L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59830L, 44L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37070L, 32L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52390L, 44L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32278L, 32L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32110L, 32L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58360L, 40L)}));
    }

    private final Object v() {
        return new nz8("string:shelf_type", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45767L, 34L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37563L, 22L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39403L, 22L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57111L, 34L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39681L, 26L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38779L, 26L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40351L, 26L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60247L, 42L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36203L, 26L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38071L, 26L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40123L, 30L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38583L, 26L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37875L, 26L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37923L, 22L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38479L, 26L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52379L, 26L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59875L, 42L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37103L, 26L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52435L, 26L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32311L, 26L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32143L, 26L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58401L, 26L)}));
    }

    private final Object w() {
        return new nz8("string:show_chapter_name", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45802L, 65L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37586L, 57L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39426L, 53L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57146L, 97L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39708L, 49L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38806L, 65L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40378L, 61L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60290L, 89L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36230L, 49L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38098L, 53L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40154L, 61L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38610L, 53L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37902L, 53L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37946L, 57L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38506L, 61L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52406L, 89L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59918L, 65L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37130L, 57L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52462L, 89L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32338L, 49L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32170L, 45L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58428L, 61L)}));
    }

    private final Object x() {
        return new nz8("string:signup_email_exist", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45868L, 102L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37644L, 54L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39480L, 58L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57244L, 70L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39758L, 54L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38872L, 54L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40440L, 58L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60380L, 102L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36280L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38152L, 54L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40216L, 78L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38664L, 78L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37956L, 50L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38004L, 54L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38568L, 50L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52496L, 70L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59984L, 86L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37188L, 54L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52552L, 58L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32388L, 54L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32216L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58490L, 58L)}));
    }

    private final Object y() {
        return new nz8("string:setting_reader_turn_page_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40323L, 173L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33375L, 145L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35059L, 141L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 50607L, 209L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 35573L, 109L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34359L, 129L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 35739L, 133L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 53579L, 217L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32107L, 129L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 33795L, 113L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35691L, 125L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34375L, 109L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33595L, 125L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33667L, 125L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34123L, 133L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46479L, 205L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53167L, 257L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 32791L, 137L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 46571L, 185L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28727L, 93L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28543L, 93L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 52375L, 141L)}));
    }

    private final Object z() {
        return new nz8("string:signup_email_invalid", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45971L, 96L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37699L, 52L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39539L, 56L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57315L, 60L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39813L, 48L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38927L, 68L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40499L, 48L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60483L, 72L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36327L, 52L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38207L, 52L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40295L, 76L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38743L, 80L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38007L, 56L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38059L, 56L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38619L, 48L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52567L, 80L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 60071L, 88L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37243L, 52L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52611L, 60L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32443L, 52L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32263L, 44L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58549L, 60L)}));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new nz8("string:setting_version_app", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 44692L, 55L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36640L, 43L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38524L, 43L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 55896L, 51L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 38850L, 43L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 37856L, 47L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39460L, 43L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 58860L, 63L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35364L, 43L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37140L, 47L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39272L, 55L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 37764L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37008L, 43L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 36996L, 43L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37548L, 43L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51168L, 51L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 58596L, 67L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36232L, 43L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51144L, 51L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31556L, 43L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31388L, 43L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57490L, 51L)}));
            case 1:
                return new nz8("string:setting_reader_turn_page", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 40751L, 92L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 33727L, 76L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35387L, 64L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51099L, 92L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 35997L, 56L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 34667L, 72L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36075L, 76L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54183L, 108L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32427L, 64L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34083L, 64L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 35983L, 60L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34655L, 64L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 33919L, 64L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 33979L, 72L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34439L, 76L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 46999L, 100L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 53731L, 124L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33119L, 68L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47075L, 116L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 28955L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 28771L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 52879L, 72L)}));
            case 2:
                return new nz8("string:settings_reader_assist", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 44748L, 66L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36684L, 54L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38568L, 42L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 55948L, 74L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 38894L, 54L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 37904L, 58L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39504L, 58L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 58924L, 90L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35408L, 50L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37188L, 54L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39328L, 46L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 37808L, 50L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37052L, 54L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37040L, 54L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37592L, 62L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51220L, 74L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 58664L, 86L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36276L, 50L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51196L, 74L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31600L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31432L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57542L, 54L)}));
            case 3:
                return new nz8("string:settings_reader_behavior", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 44815L, 64L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36739L, 64L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38611L, 52L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56023L, 88L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 38949L, 56L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 37963L, 68L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39563L, 64L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59015L, 92L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35459L, 60L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37243L, 64L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39375L, 56L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 37859L, 52L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37107L, 48L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37095L, 68L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37655L, 64L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51295L, 84L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 58751L, 92L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36327L, 56L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51271L, 96L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31647L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31479L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57597L, 60L)}));
            case 4:
                return new nz8("string:setting_restore_mode_merge", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 41194L, 66L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 34066L, 54L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 35706L, 66L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 51642L, 86L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 36284L, 50L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 35022L, 54L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 36434L, 66L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 54782L, 86L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 32750L, 54L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 34398L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 36334L, 62L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 34978L, 58L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 34234L, 62L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 34290L, 46L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 34786L, 54L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 47490L, 78L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 54326L, 70L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 33462L, 62L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 47550L, 74L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 29218L, 50L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 29034L, 50L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 53230L, 58L)}));
            case 5:
                return new nz8("string:settings_reader_content", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 44880L, 75L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36804L, 59L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38664L, 51L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56112L, 75L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39006L, 55L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38032L, 55L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39628L, 59L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59108L, 87L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35520L, 55L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37308L, 63L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39432L, 71L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 37912L, 55L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37156L, 51L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37164L, 59L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37720L, 63L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51380L, 75L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 58844L, 91L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36384L, 59L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51368L, 83L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31696L, 51L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31528L, 51L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57658L, 55L)}));
            case 6:
                return new nz8("string:settings_reader_controls", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 44956L, 76L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36864L, 60L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38716L, 60L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56188L, 80L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39062L, 60L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38088L, 56L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39688L, 60L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59196L, 100L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35576L, 60L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37372L, 56L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39504L, 68L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 37968L, 56L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37208L, 60L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37224L, 56L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37784L, 56L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51456L, 84L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 58936L, 108L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36444L, 64L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51452L, 76L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31748L, 52L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31580L, 52L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57714L, 68L)}));
            case 7:
                return new nz8("string:share", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 45073L, 29L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 36957L, 25L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 38813L, 21L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 56309L, 45L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39151L, 21L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38181L, 25L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 39781L, 25L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 59345L, 49L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 35669L, 25L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 37461L, 25L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 39597L, 21L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38049L, 21L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 37301L, 21L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 37313L, 29L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 37877L, 29L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 51581L, 41L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 59101L, 29L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 36537L, 25L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 51577L, 41L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 31825L, 21L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 31657L, 21L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 57815L, 25L)}));
            case 8:
                return b();
            case 9:
                return e();
            case 10:
                return i();
            case 11:
                return k();
            case 12:
                return l();
            case 13:
                return m();
            case 14:
                return n();
            case 15:
                return a();
            case 16:
                return p();
            case 17:
                return q();
            case 18:
                return r();
            case 19:
                return s();
            case 20:
                return t();
            case 21:
                return u();
            case 22:
                return v();
            case 23:
                return w();
            case 24:
                return x();
            case 25:
                return y();
            case 26:
                return o();
            case 27:
                return z();
            case 28:
                return A();
            default:
                return new nz8("string:signup_error", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 46068L, 144L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 37752L, 108L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 39596L, 132L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 57376L, 208L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 39862L, 100L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 38996L, 120L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 40548L, 124L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 60556L, 228L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 36380L, 104L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38260L, 116L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 40372L, 152L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 38824L, 132L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38064L, 120L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38116L, 108L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 38668L, 108L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 52648L, 148L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 60160L, 208L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37296L, 116L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 52672L, 152L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 32496L, 80L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32308L, 80L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 58610L, 120L)}));
        }
    }
}
