package defpackage;

import java.util.Map;
import java.util.Set;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: f09  reason: default package */
/* loaded from: classes3.dex */
public abstract class f09 {
    public static final Map a = oj6.S(new xy7("a", "a"), new xy7("b", "bê"), new xy7("c", "xê"), new xy7("d", "đê"), new xy7("đ", "đê"), new xy7("e", "e"), new xy7("ê", "ê"), new xy7("f", "ép"), new xy7("g", "gờ"), new xy7("h", "hát"), new xy7("i", "i"), new xy7("j", "giây"), new xy7("k", "ca"), new xy7("l", "lờ"), new xy7("m", "mờ"), new xy7("n", "nờ"), new xy7("o", "ô"), new xy7("ô", "ô"), new xy7("ơ", "ơ"), new xy7("p", "pê"), new xy7("q", "qui"), new xy7("r", "rờ"), new xy7("s", "ét"), new xy7("t", "tê"), new xy7("u", "u"), new xy7("ư", "ư"), new xy7("v", "vê"), new xy7("w", "đắp liu"), new xy7("x", "ích"), new xy7("y", "y"), new xy7("z", "dét"));
    public static final Map b = oj6.S(new xy7("km", "ki lô mét"), new xy7("dm", "đê xi mét"), new xy7("cm", "xen ti mét"), new xy7("mm", "mi li mét"), new xy7("nm", "na nô mét"), new xy7("µm", "mic rô mét"), new xy7("μm", "mic rô mét"), new xy7("m", "mét"), new xy7("kg", "ki lô gam"), new xy7("g", "gam"), new xy7("µg", "mic rô gam"), new xy7("mg", "mi li gam"), new xy7("km2", "ki lô mét vuông"), new xy7("m2", "mét vuông"), new xy7("cm2", "xen ti mét vuông"), new xy7("mm2", "mi li mét vuông"), new xy7("ha", "héc ta"), new xy7("km3", "ki lô mét khối"), new xy7("m3", "mét khối"), new xy7("cm3", "xen ti mét khối"), new xy7("mm3", "mi li mét khối"), new xy7("l", "lít"), new xy7("dl", "đê xi lít"), new xy7("ml", "mi li lít"), new xy7("hl", "héc tô lít"), new xy7("kw", "ki lô oát"), new xy7("mw", "mê ga oát"), new xy7("gw", "gi ga oát"), new xy7("kwh", "ki lô oát giờ"), new xy7("kWh", "ki lô oát giờ"), new xy7("mwh", "mê ga oát giờ"), new xy7("wh", "oát giờ"), new xy7("hz", "héc"), new xy7("khz", "ki lô héc"), new xy7("mhz", "mê ga héc"), new xy7("ghz", "gi ga héc"), new xy7("pa", a("pascal")), new xy7("kpa", a("kilopascal")), new xy7("mpa", a("megapascal")), new xy7("bar", a("bar")), new xy7("mbar", a("millibar")), new xy7("atm", a("atmosphere")), new xy7("psi", a("p s i")), new xy7("j", a("joule")), new xy7("kj", a("kilojoule")), new xy7("cal", a("calorie")), new xy7("kcal", a("kilocalorie")), new xy7("h", "giờ"), new xy7("p", "phút"), new xy7("s", "giây"), new xy7("sqm", "mét vuông"), new xy7("cum", "mét khối"), new xy7("gb", a("gigabyte")), new xy7("mb", a("megabyte")), new xy7("kb", a("kilobyte")), new xy7("tb", a("terabyte")), new xy7("db", a("decibel")), new xy7("oz", a("ounce")), new xy7("lb", a("pound")), new xy7("lbs", a("pounds")), new xy7("ft", a("feet")), new xy7("in", a("inch")), new xy7("dpi", a("d p i")), new xy7("ph", "pê hát"), new xy7("gbps", a("gigabits per second")), new xy7("mbps", a("megabits per second")), new xy7("kbps", a("kilobits per second")), new xy7("gallon", a("gallon")), new xy7("mol", "mol"), new xy7("ms", "mi li giây"), new xy7("M", "triệu"), new xy7("B", "tỷ"));
    public static final Map c = oj6.S(new xy7("usd", a("u s d")), new xy7("vnd", "việt nam đồng"), new xy7("vnđ", "việt nam đồng"), new xy7("đ", "đồng"), new xy7("v n d", "việt nam đồng"), new xy7("v n đ", "việt nam đồng"), new xy7("€", a("euro")), new xy7("euro", a("euro")), new xy7("eur", a("euro")), new xy7("¥", "yên"), new xy7("yên", "yên"), new xy7("jpy", "yên"), new xy7("%", "phần trăm"));
    public static final Map d = oj6.S(new xy7("CĐV", "cổ động viên"), new xy7("HĐND", "hội đồng nhân dân"), new xy7("HĐQT", "hội đồng quản trị"), new xy7("TAND", "toàn án nhân dân"), new xy7("BHXH", "bảo hiểm xã hội"), new xy7("BHTN", "bảo hiểm thất nghiệp"), new xy7("TP.HCM", "thành phố hồ chí minh"), new xy7("VN", "việt nam"), new xy7("UBND", "uỷ ban nhân dân"), new xy7("TP", "thành phố"), new xy7("HCM", "hồ chí minh"), new xy7("HN", "hà nội"), new xy7("BTC", "ban tổ chức"), new xy7("CLB", "câu lạc bộ"), new xy7("HTX", "hợp tác xã"), new xy7("NXB", "nhà xuất bản"), new xy7("TW", "trung ương"), new xy7("CSGT", "cảnh sát giao thông"), new xy7("LHQ", "liên hợp quốc"), bpd.m("THCS", "trung học cơ sở"), bpd.m("THPT", "trung học phổ thông"), bpd.m("ĐH", "đại học"), bpd.m("HLV", "huấn luyện viên"), bpd.m("GS", "giáo sư"), bpd.m("TS", "tiến sĩ"), bpd.m("TNHH", "trách nhiệm hữu hạn"), bpd.m("VĐV", "vận động viên"), bpd.m("TPHCM", "thành phố hồ chí minh"), bpd.m("PGS", "phó giáo sư"), bpd.m("SP500", "ét pê năm trăm"), bpd.m("PGS.TS", "phó giáo sư tiến sĩ"), bpd.m("GS.TS", "giáo sư tiến sĩ"), bpd.m("ThS", "thạc sĩ"), bpd.m("BS", "bác sĩ"), bpd.m("UAE", "u a e"), bpd.m("CUDA", "cu đa"));
    public static final Map e = oj6.S(bpd.m("JSON", a("j son")), bpd.m("VRAM", a("v ram")), bpd.m("NVIDIA", a("n v d a")), bpd.m("VN-Index", a("v n").concat(" index")), bpd.m("MS DOS", a("m s dos")), bpd.m("MS-DOS", a("m s dos")), bpd.m("B2B", a("b two b")), bpd.m("MI5", a("m i five")), bpd.m("MI6", a("m i six")), bpd.m("2FA", a("two f a")), bpd.m("TX-0", a("t x zero")), bpd.m("IPv6", a("i p v").concat(" sáu")), bpd.m("IPv4", a("i p v").concat(" bốn")), bpd.m("Washington D.C", a("washington d c")), bpd.m("Washington DC", a("washington d c")), bpd.m("HCN", "hát xê nờ"), bpd.m("HF", "hát ép"), bpd.m("KI", "ca i"), bpd.m("KOH", "ca ô hát"));
    public static final Map f = oj6.S(bpd.m("com", "com"), bpd.m("vn", a("v n")), bpd.m("net", "nét"), bpd.m("org", "o rờ gờ"), bpd.m("edu", a("edu")), bpd.m("gov", "gờ o vê"), bpd.m("io", a("i o")), bpd.m("biz", "biz"), bpd.m("info", "info"));
    public static final Map g = oj6.S(bpd.m("$", a("u s d")), bpd.m("€", a("euro")), bpd.m("¥", "yên"), bpd.m("£", a("pound")), bpd.m("₩", "won"));
    public static final Map h = oj6.S(bpd.m('I', 1), bpd.m('V', 5), bpd.m('X', 10), bpd.m('L', 50), bpd.m('C', 100), bpd.m('D', 500), bpd.m('M', 1000));
    public static final Map i = oj6.S(bpd.m("v.v", " vân vân"), bpd.m("v/v", " về việc"), bpd.m("đ/c", "địa chỉ"));
    public static final Map j = oj6.S(bpd.m('&', " và "), bpd.m('+', " cộng "), bpd.m('=', " bằng "), bpd.m('#', " thăng "), bpd.m('>', " lớn hơn "), bpd.m('<', " nhỏ hơn "), bpd.m((char) 8805, " lớn hơn hoặc bằng "), bpd.m((char) 8804, " nhỏ hơn hoặc bằng "), bpd.m((char) 177, " cộng trừ "), bpd.m((char) 8776, " xấp xỉ "), bpd.m('/', " trên "), bpd.m((char) 8594, " đến "), bpd.m((char) 247, " chia "), bpd.m('*', " sao "), bpd.m((char) 215, " nhân "), bpd.m('^', " mũ "), bpd.m('~', " khoảng "), bpd.m('%', " phần trăm "), bpd.m('$', " đô la "), bpd.m((char) 8364, " ê rô "), bpd.m((char) 163, " bảng "), bpd.m((char) 165, " yên "), bpd.m((char) 8361, " won "), bpd.m((char) 8365, " kíp "), bpd.m((char) 8369, " bê xô "), bpd.m((char) 3647, " bạc "), bpd.m((char) 937, " ôm "), bpd.m('@', " a còng "), bpd.m((char) 8800, " khác "), bpd.m((char) 8704, " với mọi "), bpd.m((char) 8719, " tích "), bpd.m((char) 8712, " thuộc "), bpd.m((char) 8721, " tổng "), bpd.m((char) 8745, " giao "), bpd.m((char) 8746, " hội "), bpd.m((char) 172, " phủ định "), bpd.m((char) 8734, " vô cùng "), bpd.m((char) 945, " an pha "), bpd.m((char) 946, " bê ta "), bpd.m((char) 947, " ga ma "), bpd.m((char) 948, " đen ta "), bpd.m((char) 949, " ép si lon "), bpd.m((char) 1013, " thuộc "), bpd.m((char) 950, " de ta "), bpd.m((char) 951, " ê ta "), bpd.m((char) 952, " thê ta "), bpd.m((char) 953, " i ô ta "), bpd.m((char) 954, " cáp ba "), bpd.m((char) 955, " lam đa "), bpd.m((char) 7463, " và "), bpd.m((char) 956, " muy "), bpd.m((char) 916, " đen ta "), bpd.m((char) 957, " nu "), bpd.m((char) 958, " xi xi "), bpd.m((char) 959, " o mi ron "), bpd.m((char) 960, " pi "), bpd.m((char) 961, " ro "), bpd.m((char) 963, " xích ma "), bpd.m((char) 964, " tao "), bpd.m((char) 965, " úp si lon "), bpd.m((char) 966, " phi "), bpd.m((char) 967, " chi "), bpd.m((char) 968, " si "), bpd.m((char) 969, " ô me ga "), bpd.m((char) 169, " bản quyền "), bpd.m((char) 189, " một phần hai "), bpd.m((char) 188, " một phần tư "), bpd.m((char) 190, " ba phần tư "), bpd.m((char) 8531, " một phần ba "), bpd.m((char) 8532, " hai phần ba "), bpd.m((char) 8533, " một phần năm "), bpd.m((char) 8534, " hai phần năm "), bpd.m((char) 8535, " ba phần năm "), bpd.m((char) 8536, " bốn phần năm "), bpd.m((char) 8538, " năm phần sáu "));
    public static final Map k = oj6.S(bpd.m((char) 8304, " không "), bpd.m((char) 185, " một "), bpd.m((char) 178, " bình phương "), bpd.m((char) 179, " lập phương "), bpd.m((char) 8308, " bốn "), bpd.m((char) 8309, " năm "), bpd.m((char) 8310, " sáu "), bpd.m((char) 8311, " bảy "), bpd.m((char) 8312, " tám "), bpd.m((char) 8313, " chín "));
    public static final Map l = oj6.S(bpd.m((char) 8320, " không "), bpd.m((char) 8321, " một "), bpd.m((char) 8322, " hai "), bpd.m((char) 8323, " ba "), bpd.m((char) 8324, " bốn "), bpd.m((char) 8325, " năm "), bpd.m((char) 8326, " sáu "), bpd.m((char) 8327, " bảy "), bpd.m((char) 8328, " tám "), bpd.m((char) 8329, " chín "));
    public static final Set m = cz.t0(new String[]{"UNESCO", "NASA", "NATO", "ASEAN", "OPEC", "SARS", "FIFA", "UNIC", "RAM", "VRAM", "COVID", "IELTS", "STEM", "SWAT", "SEAL", "WASP", "COBOL", "BASIC", "OLED", "COVAX", "BRICS", "APEC", "VUCA", "PERMA", "DINK", "MENA", "EPIC", "OASIS", "BASE", "DART", "IDEA", "CHAOS", "SMART", "FANG", "BLEU", "REST", "ERROR", "SELECT", "FROM", "WHERE", "ORDER", "BY", "LIMIT", "OFFSET", "GROUP", "HAVING", "JOIN", "LEFT", "RIGHT", "INNER", "OUTER", "ON", "AS", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE", "IS", "NULL", "TRUE", "FALSE", "CASE", "WHEN", "THEN", "ELSE", "END", "UNION", "INTERSECT", "EXCEPT", "DESC"});
    public static final Map n = oj6.S(bpd.m("gmail.com", a("gmail").concat(" chấm com")), bpd.m("yahoo.com", a("yahoo").concat(" chấm com")), bpd.m("yahoo.com.vn", a("yahoo") + " chấm com chấm " + a("v n")), bpd.m("outlook.com", a("outlook").concat(" chấm com")), bpd.m("hotmail.com", a("hotmail").concat(" chấm com")), bpd.m("icloud.com", a("icloud").concat(" chấm com")), bpd.m("fpt.vn", a("f p t") + " chấm " + a("v n")), bpd.m("fpt.com.vn", a("f p t") + " chấm com chấm " + a("v n")));
    public static final jma o = twd.k(new cr8(10));
    public static final Set p = cz.t0(new String[]{"vào", "ngày", "hôm", "hôm nay", "hôm qua", "hôm kia", "mai", "ngày mai", "ngày kia", "sinh", "sinh nhật", "kỷ niệm", "lễ", "tết", "diễn ra", "tổ chức", "thứ", "tuần", "tháng", "năm"});
    public static final Set q = cz.t0(new String[]{"cộng", "trừ", "nhân", "chia", "bằng", "sin", "cos", "tan", "log", "sqrt", "xác suất", "tỷ lệ", "tỉ lệ"});

    public static String a(String str) {
        return rs5.o("__start_en__", str, "__end_en__");
    }
}
