package defpackage;

import android.content.Context;
import android.os.Build;
import com.google.firebase.messaging.FirebaseMessaging;
import java.lang.annotation.Annotation;
import java.util.UUID;
import org.mozilla.javascript.Parser;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: i  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class i implements aj4 {
    public final /* synthetic */ int a;

    public /* synthetic */ i(int i) {
        this.a = i;
    }

    private final Object a() {
        return new nz8("string-array:community_tabs", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 10L, 175L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 10L, 119L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 10L, 115L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 10L, 195L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 10L, 99L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 10L, 115L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 10L, 127L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 10L, 243L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 10L, 103L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 10L, 111L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 10L, 119L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 10L, 107L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 10L, 107L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 10L, 127L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 10L, 127L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 10L, 207L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 10L, 219L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 10L, 119L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 10L, 215L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 10L, 91L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 10L, 83L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 10L, 123L)}));
    }

    private final Object b() {
        return new nz8("string-array:shelf_sort_by_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2985L, 170L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2573L, 154L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2589L, 158L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3581L, 250L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2445L, 134L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2629L, 174L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2637L, 166L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3721L, 274L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2469L, 134L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2653L, 150L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2477L, 106L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2541L, 138L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2545L, 158L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2653L, 158L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2641L, 170L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3373L, 230L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3669L, 222L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2537L, 138L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3409L, 238L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2293L, 110L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2253L, 110L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2803L, 150L)}));
    }

    private final Object e() {
        return new nz8("string-array:shelf_tabs", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3156L, 121L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2728L, 85L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2748L, 77L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3832L, 137L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2580L, 73L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2804L, 97L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2804L, 97L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3996L, 157L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2604L, 77L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2804L, 85L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2584L, 81L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2680L, 77L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2704L, 77L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2812L, 89L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2812L, 93L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3604L, 113L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3892L, 161L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2676L, 97L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3648L, 113L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2404L, 77L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2364L, 77L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2954L, 109L)}));
    }

    private final Object i() {
        return new nz8("string-array:split_chapter_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3278L, 190L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2814L, 162L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2826L, 150L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3970L, 242L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2654L, 126L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2902L, 162L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2902L, 162L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4154L, 306L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2682L, 178L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2890L, 154L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2666L, 106L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2758L, 130L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2782L, 170L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2902L, 170L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2906L, 158L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3718L, 202L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4054L, 262L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2774L, 170L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3762L, 230L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2482L, 110L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2442L, 106L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3064L, 146L)}));
    }

    private final Object k() {
        return new nz8("string-array:table_of_content_tabs", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3469L, 96L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2977L, 56L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2977L, 76L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4213L, 124L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2781L, 72L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3065L, 64L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3065L, 76L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4461L, 104L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2861L, 60L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3045L, 60L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2773L, 68L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2889L, 56L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2953L, 72L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3073L, 64L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3065L, 64L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3921L, 88L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4317L, 96L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2945L, 68L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3993L, 76L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2593L, 52L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2549L, 52L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3211L, 68L)}));
    }

    private final Object l() {
        return new nz8("string-array:text_scroll_type", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3566L, 151L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 3034L, 139L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 3054L, 139L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4338L, 223L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2854L, 127L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3130L, 151L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3142L, 147L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4566L, 267L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2922L, 123L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3106L, 147L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2842L, 183L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2946L, 159L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 3026L, 139L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3138L, 147L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3130L, 143L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 4010L, 243L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4414L, 227L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 3014L, 123L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4070L, 235L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2646L, 107L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2602L, 107L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3280L, 127L)}));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        FirebaseMessaging firebaseMessaging;
        switch (this.a) {
            case 0:
                return new xe();
            case 1:
                return Integer.valueOf(zp8.b.e(2147418112) + Parser.ARGC_LIMIT);
            case 2:
                return UUID.randomUUID().toString();
            case 3:
                return new dm7("com.reader.app.ui.screen.community.AddConversationRoute", j7.INSTANCE, new Annotation[0]);
            case 4:
                return le8.i(null, 0L, 7);
            case 5:
                throw new IllegalStateException("Alert not initialized");
            case 6:
                return new me(r83.b);
            case 7:
                synchronized (FirebaseMessaging.class) {
                    firebaseMessaging = FirebaseMessaging.getInstance(q54.d());
                }
                firebaseMessaging.getClass();
                return new n64(firebaseMessaging);
            case 8:
                String str = Build.VERSION.RELEASE;
                if (str == null) {
                    return "";
                }
                return str;
            case 9:
                return Integer.valueOf(Build.VERSION.SDK_INT);
            case 10:
                return new kjb(-3.4028235E38f, ged.e, ged.e);
            case 11:
                or1 or1Var = xu.a;
                return ip2.a;
            case 12:
                or1 or1Var2 = xu.a;
                return vq2.a;
            case 13:
                return tqd.l("app_config");
            case 14:
                return tqd.l("app_settings");
            case 15:
                Context context = ivc.f;
                context.getClass();
                return new ue(context);
            case 16:
                return new nz8("string-array:setting_reader_scroll_direction_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2237L, 126L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 1909L, 110L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 1937L, 106L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 2597L, 150L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 1825L, 106L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 1933L, 122L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 1953L, 114L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 2641L, 170L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 1853L, 106L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 1953L, 114L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 1877L, 90L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 1845L, 118L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 1889L, 106L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 1985L, 106L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 1957L, 122L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2465L, 158L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 2677L, 154L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 1929L, 94L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2501L, 166L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1749L, 94L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1709L, 94L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2127L, 102L)}));
            case 17:
                return new nz8("string-array:setting_reader_scroll_type_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2364L, 72L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2020L, 76L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2044L, 72L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 2748L, 80L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 1932L, 64L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2056L, 72L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2068L, 76L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 2812L, 100L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 1960L, 64L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2068L, 72L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 1968L, 84L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 1964L, 76L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 1996L, 68L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2092L, 80L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2080L, 68L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2624L, 88L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 2832L, 84L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2024L, 72L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2668L, 88L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1844L, 64L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1804L, 64L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2230L, 64L)}));
            case 18:
                return new nz8("string-array:download_range_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 186L, 107L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 130L, 107L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 126L, 119L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 206L, 167L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 110L, 99L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 126L, 127L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 138L, 123L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 254L, 163L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 114L, 87L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 122L, 115L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 130L, 91L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 118L, 107L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 118L, 127L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 138L, 139L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 138L, 127L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 218L, 139L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 230L, 155L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 130L, 103L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 226L, 167L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 102L, 87L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 94L, 91L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 134L, 119L)}));
            case 19:
                return new nz8("string-array:setting_reader_touch_turn_page_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2437L, 158L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2097L, 150L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2117L, 146L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 2829L, 282L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 1997L, 150L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2129L, 154L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2145L, 150L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 2913L, 282L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2025L, 142L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2141L, 174L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2053L, 146L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2041L, 154L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2065L, 146L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2173L, 146L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2149L, 146L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2713L, 246L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 2917L, 238L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2097L, 138L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2757L, 226L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 1909L, 118L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1869L, 126L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2295L, 150L)}));
            case 20:
                return new nz8("string-array:setting_reader_translate_detect_language_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2596L, 183L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2248L, 167L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2264L, 167L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3112L, 263L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2148L, 135L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2284L, 179L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2296L, 179L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3196L, 275L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2168L, 147L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2316L, 167L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2200L, 135L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2196L, 139L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2212L, 171L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2320L, 159L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2296L, 175L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 2960L, 223L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3156L, 323L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2236L, 147L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 2984L, 235L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2028L, 127L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 1996L, 119L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2446L, 191L)}));
            case 21:
                return new nz8("string-array:setting_swipe_back_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2780L, 138L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2416L, 90L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2432L, 90L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3376L, 138L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2284L, 94L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2464L, 98L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2476L, 94L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3472L, 182L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2316L, 86L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2484L, 102L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2336L, 74L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2336L, 138L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2384L, 94L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2480L, 106L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2472L, 102L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3184L, 122L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3480L, 122L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2384L, 86L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3220L, 122L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2156L, 70L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2116L, 70L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2638L, 98L)}));
            case 22:
                return new nz8("string-array:setting_sync_backup_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 2919L, 65L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 2507L, 65L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 2523L, 65L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 3515L, 65L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2379L, 65L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 2563L, 65L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 2571L, 65L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 3655L, 65L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 2403L, 65L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 2587L, 65L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 2411L, 65L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 2475L, 65L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 2479L, 65L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 2587L, 65L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 2575L, 65L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 3307L, 65L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 3603L, 65L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 2471L, 65L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 3343L, 65L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2227L, 65L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2187L, 65L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 2737L, 65L)}));
            case 23:
                return b();
            case 24:
                return e();
            case 25:
                return i();
            case 26:
                return a();
            case 27:
                return k();
            case 28:
                return l();
            default:
                return new nz8("string-array:translate_qt_break_segment_values", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 3718L, 104L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 3174L, 84L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 3194L, 76L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 4562L, 116L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 2982L, 80L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 3282L, 80L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 3290L, 84L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 4834L, 156L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 3046L, 80L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 3254L, 80L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 3026L, 76L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 3106L, 88L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 3166L, 76L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 3286L, 92L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 3274L, 80L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 4254L, 116L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 4642L, 124L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 3138L, 88L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 4306L, 104L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 2754L, 72L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 2710L, 68L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 3408L, 84L)}));
        }
    }
}
