package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: jaa  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class jaa implements aj4 {
    public final /* synthetic */ int a;

    private final Object A() {
        return new nz8("string:tts_auto_stop_when_exit", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 54043L, 91L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 44359L, 75L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46535L, 75L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 67131L, 111L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47648L, 55L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45815L, 75L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47559L, 75L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70863L, 127L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42571L, 71L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44879L, 71L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 47159L, 63L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45411L, 63L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44647L, 75L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44779L, 83L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45423L, 71L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61751L, 95L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 70615L, 115L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43819L, 67L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61739L, 87L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 38003L, 59L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37775L, 59L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 67363L, 71L)}));
    }

    private final Object a() {
        return new nz8("string:translate_qt_import_failed", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51543L, 90L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42207L, 74L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44271L, 98L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63907L, 110L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45644L, 74L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43607L, 82L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45287L, 98L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67563L, 110L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40575L, 66L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42731L, 86L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45079L, 106L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43327L, 98L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42579L, 82L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42607L, 90L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43171L, 82L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 58751L, 126L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 66955L, 138L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41743L, 86L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58775L, 106L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36195L, 70L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35983L, 70L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65087L, 86L)}));
    }

    private final Object b() {
        return new nz8("string:translate_qt_personal_general", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52510L, 105L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43062L, 93L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45198L, 101L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65202L, 141L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46459L, 89L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44474L, 89L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46186L, 93L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68814L, 157L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41350L, 77L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43574L, 89L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45918L, 85L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44182L, 77L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43414L, 93L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43466L, 89L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44062L, 89L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59906L, 121L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68494L, 177L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42574L, 81L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59890L, 145L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36942L, 73L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36702L, 81L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65982L, 89L)}));
    }

    private final Object e() {
        return new nz8("string:translate_qt_dic_mode_merge_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50425L, 184L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41333L, 132L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43313L, 132L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62529L, 216L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44750L, 136L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42669L, 148L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44297L, 140L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66125L, 252L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39773L, 120L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41821L, 132L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 44101L, 144L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42405L, 140L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41653L, 120L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41733L, 120L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42269L, 136L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57505L, 188L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65541L, 192L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40853L, 128L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57573L, 176L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35449L, 104L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35257L, 100L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64189L, 116L)}));
    }

    private final Object i() {
        return new nz8("string:translate_qt_personal_general_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52339L, 170L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42923L, 138L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45035L, 162L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65007L, 194L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46328L, 130L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44339L, 134L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46043L, 142L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68583L, 230L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41215L, 134L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43455L, 118L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45791L, 126L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44047L, 134L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43279L, 134L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43327L, 138L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43923L, 138L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 59723L, 182L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68131L, 362L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42451L, 122L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 59707L, 182L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36811L, 130L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36575L, 126L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65815L, 166L)}));
    }

    private final Object k() {
        return new nz8("string:translate_qt_priv_dictionary_title", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52616L, 78L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43156L, 66L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45300L, 74L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65344L, 82L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46549L, 66L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44564L, 70L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46280L, 70L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 68972L, 90L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41428L, 62L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43664L, 66L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46004L, 58L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44260L, 62L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43508L, 70L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43556L, 66L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44152L, 70L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60028L, 78L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68672L, 106L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42656L, 62L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60036L, 86L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37016L, 58L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36784L, 58L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66072L, 70L)}));
    }

    private final Object l() {
        return new nz8("string:translate_qt_secondary_dictionary_title", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52695L, 87L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43223L, 75L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45375L, 79L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65427L, 91L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46616L, 75L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44635L, 79L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46351L, 79L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69063L, 111L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41491L, 67L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43731L, 75L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46063L, 63L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44323L, 67L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43579L, 75L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43623L, 75L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44223L, 79L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60107L, 107L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68779L, 95L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42719L, 71L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60123L, 95L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37075L, 63L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36843L, 63L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66143L, 71L)}));
    }

    private final Object m() {
        return new nz8("string:translate_qt_vp", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52880L, 55L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43384L, 55L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45556L, 55L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65656L, 79L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46773L, 51L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44808L, 55L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46528L, 55L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69308L, 91L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41640L, 51L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43892L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46216L, 43L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44480L, 47L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43740L, 51L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43788L, 55L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44400L, 55L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60336L, 67L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69032L, 103L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42872L, 51L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60348L, 71L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37216L, 43L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36980L, 47L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66304L, 55L)}));
    }

    private final Object n() {
        return new nz8("string:translate_qt_vp_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52783L, 96L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43299L, 84L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45455L, 100L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65519L, 136L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46692L, 80L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44715L, 92L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46431L, 96L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69175L, 132L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41559L, 80L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43807L, 84L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46127L, 88L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44391L, 88L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43655L, 84L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43699L, 88L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44303L, 96L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60215L, 120L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 68875L, 156L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42791L, 80L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60219L, 128L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37139L, 76L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36907L, 72L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66215L, 88L)}));
    }

    private final Object o() {
        return new nz8("string:translate_save_all", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52936L, 38L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43440L, 34L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45612L, 34L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65736L, 34L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46825L, 30L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44864L, 34L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46584L, 34L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69400L, 38L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41692L, 34L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43948L, 34L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46260L, 38L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44528L, 34L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43792L, 34L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43844L, 38L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44456L, 34L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60404L, 34L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69136L, 54L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42924L, 34L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60420L, 34L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37260L, 34L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37028L, 34L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66360L, 42L)}));
    }

    private final Object p() {
        return new nz8("string:translate_save_book", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 52975L, 51L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43475L, 43L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45647L, 43L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65771L, 63L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46856L, 39L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44899L, 47L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46619L, 47L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69439L, 59L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41727L, 43L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 43983L, 51L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46299L, 43L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44563L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43827L, 39L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43883L, 43L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44491L, 47L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60439L, 51L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69191L, 59L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42959L, 39L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60455L, 47L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37295L, 35L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37063L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66403L, 47L)}));
    }

    private final Object q() {
        return new nz8("string:translate_save_extension", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53027L, 60L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43519L, 52L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45691L, 48L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65835L, 64L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46896L, 44L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44947L, 48L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46667L, 48L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69499L, 56L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41771L, 48L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44035L, 48L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46343L, 52L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44607L, 52L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43867L, 48L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43927L, 44L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44539L, 48L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60491L, 64L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69251L, 60L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 42999L, 44L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60503L, 60L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37331L, 44L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37103L, 44L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66451L, 48L)}));
    }

    private final Object r() {
        return new nz8("string:translate_save_translate", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53088L, 64L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43572L, 56L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45740L, 64L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65900L, 76L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46941L, 56L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 44996L, 64L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46716L, 60L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69556L, 76L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41820L, 56L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44084L, 56L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46396L, 48L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44660L, 52L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43916L, 52L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 43972L, 60L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44588L, 60L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60556L, 76L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69312L, 80L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43044L, 56L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60564L, 76L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37376L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37148L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66500L, 56L)}));
    }

    private final Object s() {
        return new nz8("string:translate_search_more", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53153L, 77L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43629L, 61L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45805L, 57L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 65977L, 113L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 46998L, 57L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45061L, 61L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46777L, 65L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69633L, 73L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41877L, 53L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44141L, 57L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46445L, 73L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44713L, 61L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 43969L, 49L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44033L, 61L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44649L, 65L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60633L, 93L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69393L, 141L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43101L, 57L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60641L, 97L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37425L, 53L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37197L, 53L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66557L, 73L)}));
    }

    private final Object t() {
        return new nz8("string:translate_qt_dic_mode_missing", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50873L, 105L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41657L, 81L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43657L, 85L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 63053L, 133L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45098L, 69L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43021L, 81L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44653L, 93L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66721L, 117L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40085L, 69L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42145L, 77L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 44457L, 65L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42733L, 73L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41989L, 77L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42053L, 69L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42605L, 85L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57981L, 113L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 66025L, 109L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41181L, 69L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58013L, 89L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35717L, 69L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35513L, 61L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64501L, 69L)}));
    }

    private final Object u() {
        return new nz8("string:trash_manager", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53265L, 69L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43725L, 49L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45901L, 45L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66133L, 101L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47086L, 49L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45153L, 57L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46873L, 57L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69749L, 101L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 41965L, 49L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44229L, 49L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46545L, 57L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44801L, 41L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44049L, 45L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44125L, 57L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44745L, 61L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60769L, 89L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69565L, 85L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43185L, 53L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60785L, 85L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37505L, 45L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37277L, 45L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66657L, 49L)}));
    }

    private final Object v() {
        return new nz8("string:tts_allow_headset_control", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53490L, 97L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43906L, 73L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46070L, 85L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66446L, 113L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47251L, 65L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45350L, 77L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47062L, 89L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70150L, 117L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42138L, 65L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44406L, 73L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46738L, 85L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44970L, 65L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44218L, 73L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44314L, 89L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44938L, 85L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61050L, 113L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69866L, 129L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43386L, 77L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61074L, 113L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37650L, 57L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37422L, 57L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66866L, 89L)}));
    }

    private final Object w() {
        return new nz8("string:tts_allow_headset_control_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53335L, 154L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43775L, 130L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 45947L, 122L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66235L, 210L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47136L, 114L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45211L, 138L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 46931L, 130L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 69851L, 298L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42015L, 122L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44279L, 126L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46603L, 134L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 44843L, 126L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44095L, 122L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44183L, 130L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 44807L, 130L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 60859L, 190L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69651L, 214L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43239L, 146L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 60871L, 202L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37551L, 98L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37323L, 98L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66707L, 158L)}));
    }

    private final Object x() {
        return new nz8("string:tts_api_keys", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53588L, 44L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 43980L, 36L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46156L, 32L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66560L, 32L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47317L, 32L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45428L, 36L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47152L, 32L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70268L, 32L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42204L, 32L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44480L, 36L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46824L, 32L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45036L, 32L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44292L, 36L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44404L, 36L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45024L, 40L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61164L, 32L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 69996L, 32L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43464L, 32L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61188L, 32L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37708L, 32L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37480L, 32L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66956L, 32L)}));
    }

    private final Object y() {
        return new nz8("string:tts_auto_expand_when_play", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53780L, 101L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 44148L, 89L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46332L, 81L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66772L, 129L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47473L, 61L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45604L, 85L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47328L, 89L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70536L, 109L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42356L, 73L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44660L, 97L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46972L, 65L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45212L, 65L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44448L, 81L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44572L, 93L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45200L, 85L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61396L, 157L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 70256L, 121L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43616L, 73L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61416L, 141L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37836L, 61L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37608L, 61L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 67128L, 81L)}));
    }

    private final Object z() {
        return new nz8("string:tts_auto_expand_when_play_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 53633L, 146L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 44017L, 130L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 46189L, 142L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 66593L, 178L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 47350L, 122L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 45465L, 138L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 47185L, 142L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 70301L, 234L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 42237L, 118L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 44517L, 142L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 46857L, 114L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 45069L, 142L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 44329L, 118L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 44441L, 130L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 45065L, 134L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 61197L, 198L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 70029L, 226L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 43497L, 118L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 61221L, 194L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 37741L, 94L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 37513L, 94L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 66989L, 138L)}));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new nz8("string:translate_qt_dic_action_delete", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50126L, 46L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41070L, 46L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43026L, 50L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62198L, 62L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44499L, 46L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42398L, 50L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44022L, 50L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65786L, 58L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39530L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41554L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43802L, 46L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42126L, 46L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41362L, 54L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41470L, 46L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 41998L, 50L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57202L, 58L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65206L, 46L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40578L, 42L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57262L, 62L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35206L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35014L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 63934L, 46L)}));
            case 1:
                return new nz8("string:translate_qt_dic_action_export", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50173L, 54L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41117L, 46L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43077L, 54L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62261L, 58L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44546L, 46L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42449L, 50L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44073L, 50L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65845L, 66L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39577L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41605L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43849L, 62L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42173L, 54L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41417L, 54L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41517L, 50L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42049L, 50L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57261L, 58L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65253L, 62L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40621L, 54L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57325L, 58L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35253L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35061L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 63981L, 46L)}));
            case 2:
                return new nz8("string:translate_qt_dic_action_import", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50228L, 58L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41164L, 46L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43132L, 54L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62320L, 62L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44593L, 46L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42500L, 50L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44124L, 50L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65912L, 54L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39624L, 46L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41656L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43912L, 58L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42228L, 54L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41472L, 54L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41568L, 50L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42100L, 50L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57320L, 54L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65316L, 62L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40676L, 54L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57384L, 54L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35300L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35108L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64028L, 46L)}));
            case 3:
                return new nz8("string:translate_qt_dic_import_confirm", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50287L, 59L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41211L, 55L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43187L, 55L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62383L, 63L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44640L, 47L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42551L, 51L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44175L, 51L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 65967L, 55L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39671L, 47L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41707L, 51L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 43971L, 59L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42283L, 55L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41527L, 55L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41619L, 51L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42151L, 51L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57375L, 55L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65379L, 63L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40731L, 55L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57439L, 55L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35347L, 47L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35155L, 47L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64075L, 47L)}));
            case 4:
                return new nz8("string:translate_qt_dic_import_title", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50347L, 77L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41267L, 65L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43243L, 69L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62447L, 81L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44688L, 61L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42603L, 65L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44227L, 69L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66023L, 101L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39719L, 53L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41759L, 61L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 44031L, 69L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42339L, 65L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41583L, 69L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41671L, 61L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42203L, 65L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57431L, 73L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65443L, 97L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40787L, 65L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57495L, 77L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35395L, 53L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35203L, 53L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64123L, 65L)}));
            case 5:
                return new nz8("string:split_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 46975L, 49L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38507L, 45L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40359L, 41L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58503L, 69L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40545L, 41L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 39767L, 45L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41323L, 49L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 61707L, 93L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37055L, 33L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 38971L, 41L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41223L, 49L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39591L, 41L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38791L, 45L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 38879L, 45L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39403L, 45L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53707L, 61L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61299L, 45L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 37999L, 41L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53719L, 65L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33095L, 37L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 32887L, 29L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 59377L, 41L)}));
            case 6:
                return new nz8("string:split_word_count", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 47189L, 52L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 38705L, 44L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 40541L, 44L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 58773L, 72L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 40719L, 44L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 39961L, 52L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 41521L, 52L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 62025L, 88L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 37225L, 44L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 39153L, 48L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 41417L, 36L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 39761L, 40L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 38989L, 44L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 39065L, 44L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 39597L, 52L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 53977L, 76L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 61541L, 68L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 38181L, 48L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 53993L, 72L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 33257L, 32L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 33041L, 36L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 59575L, 44L)}));
            case 7:
                return new nz8("string:translate_qt_dic_mode_merge", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 50610L, 63L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 41466L, 59L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 43446L, 71L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 62746L, 83L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 44887L, 59L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 42818L, 63L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 44438L, 71L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 66378L, 99L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 39894L, 55L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 41954L, 59L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 44246L, 59L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 42546L, 55L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 41774L, 67L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 41854L, 55L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 42406L, 63L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 57694L, 83L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 65734L, 83L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 40982L, 67L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 57750L, 79L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 35554L, 51L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 35358L, 51L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 64306L, 59L)}));
            case 8:
                return b();
            case 9:
                return e();
            case 10:
                return i();
            case 11:
                return k();
            case 12:
                return l();
            case 13:
                return m();
            case 14:
                return n();
            case 15:
                return o();
            case 16:
                return p();
            case 17:
                return q();
            case 18:
                return a();
            case 19:
                return r();
            case 20:
                return s();
            case 21:
                return t();
            case 22:
                return u();
            case 23:
                return v();
            case 24:
                return w();
            case 25:
                return x();
            case 26:
                return y();
            case 27:
                return z();
            case 28:
                return A();
            default:
                return new nz8("string:translate_qt_import_success", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 51634L, 103L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 42282L, 87L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 44370L, 91L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 64018L, 147L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 45719L, 83L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 43690L, 87L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 45386L, 91L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 67674L, 107L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 40642L, 71L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 42818L, 87L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 45186L, 107L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 43426L, 103L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 42662L, 95L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 42698L, 87L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 43254L, 87L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 58878L, 115L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 67094L, 127L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 41830L, 99L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 58882L, 115L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 36266L, 71L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 36054L, 71L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 65174L, 87L)}));
        }
    }
}
