package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: kjd  reason: default package */
/* loaded from: classes.dex */
public final class kjd implements wl7 {
    public static final kjd a = new Object();
    public static final b24 b = new b24(h12.p(jlb.p(a9d.class, new e5d(1))), "systemInfo");
    public static final b24 c = new b24(h12.p(jlb.p(a9d.class, new e5d(2))), "eventName");
    public static final b24 d = new b24(h12.p(jlb.p(a9d.class, new e5d(37))), "isThickClient");
    public static final b24 e = new b24(h12.p(jlb.p(a9d.class, new e5d(61))), "clientType");
    public static final b24 f = new b24(h12.p(jlb.p(a9d.class, new e5d(3))), "modelDownloadLogEvent");
    public static final b24 g = new b24(h12.p(jlb.p(a9d.class, new e5d(20))), "customModelLoadLogEvent");
    public static final b24 h = new b24(h12.p(jlb.p(a9d.class, new e5d(4))), "customModelInferenceLogEvent");
    public static final b24 i = new b24(h12.p(jlb.p(a9d.class, new e5d(29))), "customModelCreateLogEvent");
    public static final b24 j = new b24(h12.p(jlb.p(a9d.class, new e5d(5))), "onDeviceFaceDetectionLogEvent");
    public static final b24 k = new b24(h12.p(jlb.p(a9d.class, new e5d(59))), "onDeviceFaceLoadLogEvent");
    public static final b24 l = new b24(h12.p(jlb.p(a9d.class, new e5d(6))), "onDeviceTextDetectionLogEvent");
    public static final b24 m = new b24(h12.p(jlb.p(a9d.class, new e5d(79))), "onDeviceTextDetectionLoadLogEvent");
    public static final b24 n = new b24(h12.p(jlb.p(a9d.class, new e5d(7))), "onDeviceBarcodeDetectionLogEvent");
    public static final b24 o = new b24(h12.p(jlb.p(a9d.class, new e5d(58))), "onDeviceBarcodeLoadLogEvent");
    public static final b24 p = new b24(h12.p(jlb.p(a9d.class, new e5d(48))), "onDeviceImageLabelCreateLogEvent");
    public static final b24 q = new b24(h12.p(jlb.p(a9d.class, new e5d(49))), "onDeviceImageLabelLoadLogEvent");
    public static final b24 r = new b24(h12.p(jlb.p(a9d.class, new e5d(18))), "onDeviceImageLabelDetectionLogEvent");
    public static final b24 s = new b24(h12.p(jlb.p(a9d.class, new e5d(26))), "onDeviceObjectCreateLogEvent");
    public static final b24 t = new b24(h12.p(jlb.p(a9d.class, new e5d(27))), "onDeviceObjectLoadLogEvent");
    public static final b24 u = new b24(h12.p(jlb.p(a9d.class, new e5d(28))), "onDeviceObjectInferenceLogEvent");
    public static final b24 v = new b24(h12.p(jlb.p(a9d.class, new e5d(44))), "onDevicePoseDetectionLogEvent");
    public static final b24 w = new b24(h12.p(jlb.p(a9d.class, new e5d(45))), "onDeviceSegmentationLogEvent");
    public static final b24 x = new b24(h12.p(jlb.p(a9d.class, new e5d(19))), "onDeviceSmartReplyLogEvent");
    public static final b24 y = new b24(h12.p(jlb.p(a9d.class, new e5d(21))), "onDeviceLanguageIdentificationLogEvent");
    public static final b24 z = new b24(h12.p(jlb.p(a9d.class, new e5d(22))), "onDeviceTranslationLogEvent");
    public static final b24 A = new b24(h12.p(jlb.p(a9d.class, new e5d(8))), "cloudFaceDetectionLogEvent");
    public static final b24 B = new b24(h12.p(jlb.p(a9d.class, new e5d(9))), "cloudCropHintDetectionLogEvent");
    public static final b24 C = new b24(h12.p(jlb.p(a9d.class, new e5d(10))), "cloudDocumentTextDetectionLogEvent");
    public static final b24 D = new b24(h12.p(jlb.p(a9d.class, new e5d(11))), "cloudImagePropertiesDetectionLogEvent");
    public static final b24 E = new b24(h12.p(jlb.p(a9d.class, new e5d(12))), "cloudImageLabelDetectionLogEvent");
    public static final b24 F = new b24(h12.p(jlb.p(a9d.class, new e5d(13))), "cloudLandmarkDetectionLogEvent");
    public static final b24 G = new b24(h12.p(jlb.p(a9d.class, new e5d(14))), "cloudLogoDetectionLogEvent");
    public static final b24 H = new b24(h12.p(jlb.p(a9d.class, new e5d(15))), "cloudSafeSearchDetectionLogEvent");
    public static final b24 I = new b24(h12.p(jlb.p(a9d.class, new e5d(16))), "cloudTextDetectionLogEvent");
    public static final b24 J = new b24(h12.p(jlb.p(a9d.class, new e5d(17))), "cloudWebSearchDetectionLogEvent");
    public static final b24 K = new b24(h12.p(jlb.p(a9d.class, new e5d(23))), "automlImageLabelingCreateLogEvent");
    public static final b24 L = new b24(h12.p(jlb.p(a9d.class, new e5d(24))), "automlImageLabelingLoadLogEvent");
    public static final b24 M = new b24(h12.p(jlb.p(a9d.class, new e5d(25))), "automlImageLabelingInferenceLogEvent");
    public static final b24 N = new b24(h12.p(jlb.p(a9d.class, new e5d(39))), "isModelDownloadedLogEvent");
    public static final b24 O = new b24(h12.p(jlb.p(a9d.class, new e5d(40))), "deleteModelLogEvent");
    public static final b24 P = new b24(h12.p(jlb.p(a9d.class, new e5d(30))), "aggregatedAutomlImageLabelingInferenceLogEvent");
    public static final b24 Q = new b24(h12.p(jlb.p(a9d.class, new e5d(31))), "aggregatedCustomModelInferenceLogEvent");
    public static final b24 R = new b24(h12.p(jlb.p(a9d.class, new e5d(32))), "aggregatedOnDeviceFaceDetectionLogEvent");
    public static final b24 S = new b24(h12.p(jlb.p(a9d.class, new e5d(33))), "aggregatedOnDeviceBarcodeDetectionLogEvent");
    public static final b24 T = new b24(h12.p(jlb.p(a9d.class, new e5d(34))), "aggregatedOnDeviceImageLabelDetectionLogEvent");
    public static final b24 U = new b24(h12.p(jlb.p(a9d.class, new e5d(35))), "aggregatedOnDeviceObjectInferenceLogEvent");
    public static final b24 V = new b24(h12.p(jlb.p(a9d.class, new e5d(36))), "aggregatedOnDeviceTextDetectionLogEvent");
    public static final b24 W = new b24(h12.p(jlb.p(a9d.class, new e5d(46))), "aggregatedOnDevicePoseDetectionLogEvent");
    public static final b24 X = new b24(h12.p(jlb.p(a9d.class, new e5d(47))), "aggregatedOnDeviceSegmentationLogEvent");
    public static final b24 Y = new b24(h12.p(jlb.p(a9d.class, new e5d(69))), "pipelineAccelerationInferenceEvents");
    public static final b24 Z = new b24(h12.p(jlb.p(a9d.class, new e5d(42))), "remoteConfigLogEvent");
    public static final b24 a0 = new b24(h12.p(jlb.p(a9d.class, new e5d(50))), "inputImageConstructionLogEvent");
    public static final b24 b0 = new b24(h12.p(jlb.p(a9d.class, new e5d(51))), "leakedHandleEvent");
    public static final b24 c0 = new b24(h12.p(jlb.p(a9d.class, new e5d(52))), "cameraSourceLogEvent");
    public static final b24 d0 = new b24(h12.p(jlb.p(a9d.class, new e5d(53))), "imageLabelOptionalModuleLogEvent");
    public static final b24 e0 = new b24(h12.p(jlb.p(a9d.class, new e5d(54))), "languageIdentificationOptionalModuleLogEvent");
    public static final b24 f0 = new b24(h12.p(jlb.p(a9d.class, new e5d(60))), "faceDetectionOptionalModuleLogEvent");
    public static final b24 g0 = new b24(h12.p(jlb.p(a9d.class, new e5d(55))), "nlClassifierOptionalModuleLogEvent");
    public static final b24 h0 = new b24(h12.p(jlb.p(a9d.class, new e5d(56))), "nlClassifierClientLibraryLogEvent");
    public static final b24 i0 = new b24(h12.p(jlb.p(a9d.class, new e5d(57))), "accelerationAllowlistLogEvent");
    public static final b24 j0 = new b24(h12.p(jlb.p(a9d.class, new e5d(62))), "toxicityDetectionCreateEvent");
    public static final b24 k0 = new b24(h12.p(jlb.p(a9d.class, new e5d(63))), "toxicityDetectionLoadEvent");
    public static final b24 l0 = new b24(h12.p(jlb.p(a9d.class, new e5d(64))), "toxicityDetectionInferenceEvent");
    public static final b24 m0 = new b24(h12.p(jlb.p(a9d.class, new e5d(65))), "barcodeDetectionOptionalModuleLogEvent");
    public static final b24 n0 = new b24(h12.p(jlb.p(a9d.class, new e5d(66))), "customImageLabelOptionalModuleLogEvent");
    public static final b24 o0 = new b24(h12.p(jlb.p(a9d.class, new e5d(67))), "codeScannerScanApiEvent");
    public static final b24 p0 = new b24(h12.p(jlb.p(a9d.class, new e5d(68))), "codeScannerOptionalModuleEvent");
    public static final b24 q0 = new b24(h12.p(jlb.p(a9d.class, new e5d(70))), "onDeviceExplicitContentCreateLogEvent");
    public static final b24 r0 = new b24(h12.p(jlb.p(a9d.class, new e5d(71))), "onDeviceExplicitContentLoadLogEvent");
    public static final b24 s0 = new b24(h12.p(jlb.p(a9d.class, new e5d(72))), "onDeviceExplicitContentInferenceLogEvent");
    public static final b24 t0 = new b24(h12.p(jlb.p(a9d.class, new e5d(73))), "aggregatedOnDeviceExplicitContentLogEvent");
    public static final b24 u0 = new b24(h12.p(jlb.p(a9d.class, new e5d(74))), "onDeviceSelfieFaceCreateLogEvent");
    public static final b24 v0 = new b24(h12.p(jlb.p(a9d.class, new e5d(75))), "onDeviceSelfieFaceLoadLogEvent");
    public static final b24 w0 = new b24(h12.p(jlb.p(a9d.class, new e5d(76))), "onDeviceSelfieFaceLogEvent");
    public static final b24 x0 = new b24(h12.p(jlb.p(a9d.class, new e5d(77))), "aggregatedOnDeviceSelfieFaceLogEvent");
    public static final b24 y0 = new b24(h12.p(jlb.p(a9d.class, new e5d(78))), "smartReplyOptionalModuleLogEvent");

    @Override // defpackage.oj3
    public final void a(Object obj, Object obj2) {
        gsd gsdVar = (gsd) obj;
        xl7 xl7Var = (xl7) obj2;
        xl7Var.a(b, gsdVar.a);
        xl7Var.a(c, gsdVar.b);
        xl7Var.a(d, null);
        xl7Var.a(e, gsdVar.c);
        xl7Var.a(f, null);
        xl7Var.a(g, null);
        xl7Var.a(h, null);
        xl7Var.a(i, null);
        xl7Var.a(j, null);
        xl7Var.a(k, null);
        xl7Var.a(l, null);
        xl7Var.a(m, null);
        xl7Var.a(n, null);
        xl7Var.a(o, null);
        xl7Var.a(p, null);
        xl7Var.a(q, null);
        xl7Var.a(r, null);
        xl7Var.a(s, null);
        xl7Var.a(t, null);
        xl7Var.a(u, null);
        xl7Var.a(v, null);
        xl7Var.a(w, null);
        xl7Var.a(x, null);
        xl7Var.a(y, gsdVar.d);
        xl7Var.a(z, null);
        xl7Var.a(A, null);
        xl7Var.a(B, null);
        xl7Var.a(C, null);
        xl7Var.a(D, null);
        xl7Var.a(E, null);
        xl7Var.a(F, null);
        xl7Var.a(G, null);
        xl7Var.a(H, null);
        xl7Var.a(I, null);
        xl7Var.a(J, null);
        xl7Var.a(K, null);
        xl7Var.a(L, null);
        xl7Var.a(M, null);
        xl7Var.a(N, null);
        xl7Var.a(O, null);
        xl7Var.a(P, null);
        xl7Var.a(Q, null);
        xl7Var.a(R, null);
        xl7Var.a(S, null);
        xl7Var.a(T, null);
        xl7Var.a(U, null);
        xl7Var.a(V, null);
        xl7Var.a(W, null);
        xl7Var.a(X, null);
        xl7Var.a(Y, null);
        xl7Var.a(Z, null);
        xl7Var.a(a0, null);
        xl7Var.a(b0, null);
        xl7Var.a(c0, null);
        xl7Var.a(d0, null);
        xl7Var.a(e0, null);
        xl7Var.a(f0, null);
        xl7Var.a(g0, null);
        xl7Var.a(h0, null);
        xl7Var.a(i0, null);
        xl7Var.a(j0, null);
        xl7Var.a(k0, null);
        xl7Var.a(l0, null);
        xl7Var.a(m0, null);
        xl7Var.a(n0, null);
        xl7Var.a(o0, null);
        xl7Var.a(p0, null);
        xl7Var.a(q0, null);
        xl7Var.a(r0, null);
        xl7Var.a(s0, null);
        xl7Var.a(t0, null);
        xl7Var.a(u0, null);
        xl7Var.a(v0, null);
        xl7Var.a(w0, null);
        xl7Var.a(x0, null);
        xl7Var.a(y0, null);
    }
}
