package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: n9a  reason: default package */
/* loaded from: classes3.dex */
public final /* synthetic */ class n9a implements aj4 {
    public final /* synthetic */ int a;

    private final Object A() {
        return new nz8("string:import_from_browser", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22227L, 75L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18527L, 63L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19685L, 59L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28531L, 111L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20669L, 55L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19103L, 59L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19779L, 67L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30471L, 103L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17865L, 51L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18831L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20539L, 71L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19495L, 71L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 19009L, 63L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18547L, 59L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18935L, 55L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25915L, 75L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29831L, 107L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18279L, 59L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25815L, 83L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 16087L, 51L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15919L, 51L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33355L, 63L)}));
    }

    private final Object a() {
        return new nz8("string:episode_count", cz.t0(new a09[]{new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15211L, 41L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 15375L, 41L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13855L, 41L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14811L, 49L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 26376L, 37L)}));
    }

    private final Object b() {
        return new nz8("string:extension_unpin", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20266L, 59L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16870L, 35L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17760L, 35L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25970L, 55L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18980L, 31L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17494L, 35L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18078L, 43L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27870L, 63L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16184L, 43L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17226L, 47L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18714L, 39L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17746L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17204L, 35L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16930L, 35L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17362L, 35L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23666L, 47L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27342L, 67L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16666L, 51L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23550L, 51L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14690L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14514L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31450L, 35L)}));
    }

    private final Object e() {
        return new nz8("string:feature_not_support", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20326L, 95L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16906L, 83L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17796L, 91L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26026L, 147L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19012L, 83L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17530L, 87L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18122L, 83L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27934L, 151L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16228L, 75L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17274L, 83L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18754L, 119L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17790L, 107L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17240L, 95L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16966L, 87L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17398L, 75L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23714L, 119L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27410L, 139L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16718L, 79L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23602L, 119L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14730L, 75L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14554L, 79L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31486L, 107L)}));
    }

    private final Object i() {
        return new nz8("string:feature_request", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20422L, 51L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16990L, 43L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17888L, 47L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26174L, 75L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19096L, 43L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17618L, 47L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18206L, 63L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 28086L, 63L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16304L, 39L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17358L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18874L, 39L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17898L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17336L, 43L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17054L, 47L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17474L, 51L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23834L, 59L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27550L, 67L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16798L, 47L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23722L, 71L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14806L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14634L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31594L, 51L)}));
    }

    private final Object k() {
        return new nz8("string:feedback", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20474L, 52L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17034L, 48L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17936L, 36L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26250L, 60L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19140L, 36L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17666L, 40L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18270L, 48L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 28150L, 84L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16344L, 40L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17414L, 36L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18914L, 56L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17942L, 44L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17380L, 40L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17102L, 36L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17526L, 36L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23894L, 56L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27618L, 68L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16846L, 44L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23794L, 60L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14846L, 32L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14674L, 32L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31646L, 40L)}));
    }

    private final Object l() {
        return new nz8("string:follow", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20836L, 30L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17336L, 26L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 18502L, 22L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26720L, 50L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19618L, 22L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17952L, 22L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18564L, 22L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 28684L, 38L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16806L, 22L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17692L, 22L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 19256L, 30L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 18276L, 26L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17858L, 22L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17372L, 26L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17816L, 22L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 24292L, 38L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 28060L, 38L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17120L, 26L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 24184L, 46L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15088L, 22L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14920L, 22L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32168L, 26L)}));
    }

    private final Object m() {
        return new nz8("string:follow_add_success", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20527L, 102L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17083L, 86L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17973L, 90L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26311L, 130L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19177L, 66L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17707L, 82L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18319L, 82L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 28235L, 130L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16385L, 70L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17451L, 82L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18971L, 94L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17987L, 94L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17421L, 66L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17139L, 74L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17563L, 90L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23951L, 106L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27687L, 126L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16891L, 66L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23855L, 106L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14879L, 66L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14707L, 70L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31687L, 82L)}));
    }

    private final Object n() {
        return new nz8("string:follow_new_chapter_notification", cz.t0(new a09[]{new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 18064L, 87L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19244L, 75L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16456L, 67L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17488L, 75L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31770L, 75L)}));
    }

    private final Object o() {
        return new nz8("string:empty_install_repo", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 16732L, 78L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14116L, 54L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 14820L, 58L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 21464L, 86L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 15008L, 54L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 14584L, 58L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15172L, 66L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23016L, 126L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13512L, 54L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14420L, 50L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15404L, 70L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 14568L, 62L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14436L, 58L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14224L, 50L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14448L, 66L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 19692L, 86L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 22548L, 114L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 13928L, 46L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 19764L, 66L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12336L, 46L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12192L, 46L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 25898L, 66L)}));
    }

    private final Object p() {
        return new nz8("string:follow_new_content_notification", cz.t0(new a09[]{new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 18152L, 91L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19320L, 75L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16524L, 71L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17564L, 67L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31846L, 79L)}));
    }

    private final Object q() {
        return new nz8("string:go_link_des", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21044L, 107L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17500L, 87L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 18658L, 83L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 26972L, 163L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19770L, 83L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18116L, 83L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18724L, 79L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 28928L, 155L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16954L, 79L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17848L, 79L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 19436L, 91L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 18444L, 91L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18014L, 79L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17540L, 87L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17964L, 75L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 24508L, 123L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 28292L, 163L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17284L, 83L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 24428L, 123L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15228L, 67L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15060L, 67L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32336L, 91L)}));
    }

    private final Object r() {
        return new nz8("string:image", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21613L, 25L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17965L, 25L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19095L, 21L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 27681L, 29L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20191L, 21L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18565L, 21L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19205L, 21L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 29605L, 33L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17375L, 21L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18285L, 25L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 19909L, 21L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 18901L, 25L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18463L, 29L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17997L, 21L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18405L, 21L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25153L, 45L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29021L, 37L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17749L, 25L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25057L, 41L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15621L, 21L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15457L, 21L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32813L, 21L)}));
    }

    private final Object s() {
        return new nz8("string:follow_new_episode_notification", cz.t0(new a09[]{new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 18244L, 87L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 19396L, 75L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16596L, 71L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17632L, 75L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31926L, 71L)}));
    }

    private final Object t() {
        return new nz8("string:image_count", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21573L, 39L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17925L, 39L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19059L, 35L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 27633L, 47L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20155L, 35L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18525L, 39L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19169L, 35L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 29557L, 47L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17339L, 35L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18245L, 39L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 19873L, 35L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 18857L, 43L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18419L, 43L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 17957L, 39L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18369L, 35L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25097L, 55L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 28981L, 39L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17713L, 35L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25005L, 51L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15581L, 39L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15417L, 39L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32777L, 35L)}));
    }

    private final Object u() {
        return new nz8("string:import_extension_failed", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21639L, 99L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 17991L, 95L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19117L, 115L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 27711L, 155L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20213L, 91L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18587L, 91L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19227L, 107L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 29639L, 147L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17397L, 91L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18311L, 115L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 19931L, 103L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 18927L, 103L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18493L, 111L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18019L, 95L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18427L, 87L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25199L, 139L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29059L, 151L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17775L, 75L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25099L, 143L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15643L, 75L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15479L, 67L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32835L, 95L)}));
    }

    private final Object v() {
        return new nz8("string:import_extension_success", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21739L, 92L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18087L, 80L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19233L, 84L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 27867L, 108L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20305L, 72L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18679L, 72L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19335L, 76L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 29787L, 148L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17489L, 72L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18427L, 76L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20035L, 88L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19031L, 100L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18605L, 72L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18115L, 72L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18515L, 76L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25339L, 104L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29211L, 108L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17851L, 68L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25243L, 96L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15719L, 64L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15547L, 56L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 32931L, 84L)}));
    }

    private final Object w() {
        return new nz8("string:import_failed", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21832L, 73L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18168L, 57L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19318L, 73L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 27976L, 97L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20378L, 53L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18752L, 65L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19412L, 77L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 29936L, 85L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17562L, 53L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18504L, 65L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20124L, 101L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19132L, 85L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18678L, 65L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18188L, 73L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18592L, 65L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25444L, 105L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29320L, 105L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17920L, 69L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25340L, 85L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15784L, 57L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15604L, 57L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33016L, 61L)}));
    }

    private final Object x() {
        return new nz8("string:import_file", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21963L, 47L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18279L, 43L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19445L, 43L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28143L, 63L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20477L, 35L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18871L, 43L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19543L, 47L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30111L, 71L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17657L, 35L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18615L, 35L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20303L, 59L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19275L, 47L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18801L, 43L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18311L, 39L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18711L, 43L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25611L, 51L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29495L, 59L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18039L, 43L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25503L, 63L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15891L, 35L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15711L, 35L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33123L, 35L)}));
    }

    private final Object y() {
        return new nz8("string:import_files", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 21906L, 56L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18226L, 52L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19392L, 52L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28074L, 68L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20432L, 44L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18818L, 52L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19490L, 52L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30022L, 88L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17616L, 40L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18570L, 44L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20226L, 76L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19218L, 56L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18744L, 56L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18262L, 48L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18658L, 52L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25550L, 60L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29426L, 68L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 17990L, 48L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25426L, 76L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15842L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15662L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33078L, 44L)}));
    }

    private final Object z() {
        return new nz8("string:import_font_success", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22011L, 95L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18323L, 91L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19489L, 99L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28207L, 119L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20513L, 75L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 18915L, 87L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19591L, 83L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30183L, 135L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17693L, 79L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18651L, 87L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20363L, 79L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19323L, 79L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18845L, 79L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18351L, 87L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18755L, 87L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25663L, 115L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29555L, 115L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18083L, 87L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25567L, 103L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15927L, 71L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15747L, 79L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33159L, 91L)}));
    }

    @Override // defpackage.aj4
    public final Object invoke() {
        switch (this.a) {
            case 0:
                return new nz8("string:extension_setting_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 19718L, 86L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16442L, 82L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17312L, 90L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25366L, 110L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18600L, 70L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17054L, 90L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17654L, 90L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27186L, 174L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 15772L, 78L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 16818L, 90L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18270L, 86L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17330L, 82L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 16800L, 78L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16522L, 74L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 16930L, 90L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23086L, 110L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 26614L, 158L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16274L, 74L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 22982L, 114L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14326L, 62L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14162L, 58L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 30974L, 110L)}));
            case 1:
                return new nz8("string:extension_storage", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20204L, 61L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16816L, 53L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17710L, 49L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25900L, 69L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18934L, 45L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17440L, 53L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 18032L, 45L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27784L, 85L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16134L, 49L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17180L, 45L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18652L, 61L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17696L, 49L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17158L, 45L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16880L, 49L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17308L, 53L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23588L, 77L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27228L, 113L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16620L, 45L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23480L, 69L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14648L, 41L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14472L, 41L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31396L, 53L)}));
            case 2:
                return new nz8("string:extension_storage_desc", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 19855L, 166L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16567L, 102L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17449L, 114L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25527L, 178L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18709L, 98L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17191L, 110L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17787L, 106L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27419L, 162L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 15893L, 102L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 16951L, 94L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18391L, 102L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17447L, 102L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 16921L, 94L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16639L, 98L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17067L, 106L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23247L, 138L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 26839L, 186L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16387L, 98L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23155L, 138L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14423L, 98L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14255L, 90L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31127L, 106L)}));
            case 3:
                return new nz8("string:empty_install_extension_description", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 16321L, 183L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 13765L, 139L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 14421L, 159L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 20813L, 299L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 14681L, 139L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 14237L, 139L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 14785L, 159L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 22317L, 291L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13173L, 139L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14073L, 143L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 14957L, 187L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 14169L, 163L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14073L, 147L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 13853L, 167L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14085L, 151L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 19153L, 219L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 21885L, 299L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 13577L, 151L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 19269L, 195L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12045L, 123L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 11913L, 115L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 25459L, 195L)}));
            case 4:
                return new nz8("string:extension_storage_empty", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20022L, 83L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16670L, 63L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17564L, 59L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25706L, 103L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18808L, 51L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17302L, 59L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17894L, 59L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27582L, 107L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 15996L, 59L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17046L, 55L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18494L, 83L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17550L, 75L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17016L, 59L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16738L, 59L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17174L, 55L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23386L, 103L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27026L, 111L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16486L, 51L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23294L, 87L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14522L, 55L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14346L, 55L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31234L, 75L)}));
            case 5:
                return new nz8("string:end_last_chapter", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 17122L, 72L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 14442L, 64L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 15146L, 64L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 21982L, 116L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 15318L, 56L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 14930L, 68L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 15534L, 60L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 23590L, 104L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 13802L, 52L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 14746L, 64L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 15786L, 60L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 14946L, 60L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 14754L, 56L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 14526L, 60L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 14806L, 64L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 20106L, 76L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 23114L, 104L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 14250L, 48L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 20174L, 96L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 12614L, 48L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 12466L, 48L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 26319L, 56L)}));
            case 6:
                return new nz8("string:extension_storage_key", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20106L, 49L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16734L, 37L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17624L, 45L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25810L, 45L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18860L, 33L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17362L, 37L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17954L, 37L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27690L, 49L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16056L, 37L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17102L, 37L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18578L, 37L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17626L, 33L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17076L, 41L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16798L, 37L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17230L, 37L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23490L, 41L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27138L, 45L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16538L, 41L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23382L, 41L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14578L, 33L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14402L, 33L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31310L, 37L)}));
            case 7:
                return new nz8("string:extension_storage_value", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 20156L, 47L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 16772L, 43L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 17670L, 39L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 25856L, 43L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 18894L, 39L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 17400L, 39L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 17992L, 39L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 27740L, 43L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 16094L, 39L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 17140L, 39L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 18616L, 35L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 17660L, 35L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 17118L, 39L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 16836L, 43L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 17268L, 39L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 23532L, 55L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 27184L, 43L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 16580L, 39L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 23424L, 55L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 14612L, 35L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 14436L, 35L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 31348L, 47L)}));
            case 8:
                return b();
            case 9:
                return e();
            case 10:
                return i();
            case 11:
                return k();
            case 12:
                return l();
            case 13:
                return m();
            case 14:
                return n();
            case 15:
                return o();
            case 16:
                return a();
            case 17:
                return p();
            case 18:
                return r();
            case 19:
                return s();
            case 20:
                return t();
            case 21:
                return u();
            case 22:
                return v();
            case 23:
                return w();
            case 24:
                return x();
            case 25:
                return y();
            case 26:
                return z();
            case 27:
                return A();
            case 28:
                return q();
            default:
                return new nz8("string:import_from_browser_description", cz.t0(new a09[]{new a09(h12.q("ar"), "composeResources/com.reader.resources/values-ar/strings.commonMain.cvr", 22107L, 119L), new a09(h12.q("cs"), "composeResources/com.reader.resources/values-cs/strings.commonMain.cvr", 18415L, 111L), new a09(h12.q("de"), "composeResources/com.reader.resources/values-de/strings.commonMain.cvr", 19589L, 95L), new a09(h12.q("el"), "composeResources/com.reader.resources/values-el/strings.commonMain.cvr", 28327L, 203L), new a09(h12.q("en"), "composeResources/com.reader.resources/values-en/strings.commonMain.cvr", 20589L, 79L), new a09(h12.q("es"), "composeResources/com.reader.resources/values-es/strings.commonMain.cvr", 19003L, 99L), new a09(h12.q("fr"), "composeResources/com.reader.resources/values-fr/strings.commonMain.cvr", 19675L, 103L), new a09(h12.q("hi"), "composeResources/com.reader.resources/values-hi/strings.commonMain.cvr", 30319L, 151L), new a09(h12.q("in"), "composeResources/com.reader.resources/values-in/strings.commonMain.cvr", 17773L, 91L), new a09(h12.q("it"), "composeResources/com.reader.resources/values-it/strings.commonMain.cvr", 18739L, 91L), new a09(h12.q("ja"), "composeResources/com.reader.resources/values-ja/strings.commonMain.cvr", 20443L, 95L), new a09(h12.q("ko"), "composeResources/com.reader.resources/values-ko/strings.commonMain.cvr", 19403L, 91L), new a09(h12.q("nl"), "composeResources/com.reader.resources/values-nl/strings.commonMain.cvr", 18925L, 83L), new a09(h12.q("pl"), "composeResources/com.reader.resources/values-pl/strings.commonMain.cvr", 18439L, 107L), new a09(h12.q("pt"), "composeResources/com.reader.resources/values-pt/strings.commonMain.cvr", 18843L, 91L), new a09(h12.q("ru"), "composeResources/com.reader.resources/values-ru/strings.commonMain.cvr", 25779L, 135L), new a09(h12.q("th"), "composeResources/com.reader.resources/values-th/strings.commonMain.cvr", 29671L, 159L), new a09(h12.q("tr"), "composeResources/com.reader.resources/values-tr/strings.commonMain.cvr", 18171L, 107L), new a09(h12.q("uk"), "composeResources/com.reader.resources/values-uk/strings.commonMain.cvr", 25671L, 143L), new a09(cz.t0(new uo8[]{new bw5("zh"), new jv8("TW")}), "composeResources/com.reader.resources/values-zh-rTW/strings.commonMain.cvr", 15999L, 87L), new a09(h12.q("zh"), "composeResources/com.reader.resources/values-zh/strings.commonMain.cvr", 15827L, 91L), new a09(kj3.a, "composeResources/com.reader.resources/values/strings.commonMain.cvr", 33251L, 103L)}));
        }
    }
}
