package defpackage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Parser;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: umd  reason: default package */
/* loaded from: classes.dex */
public abstract class umd {
    public static final tmd A;
    public static final tmd A0;
    public static final tmd B;
    public static final tmd B0;
    public static final tmd C;
    public static final tmd C0;
    public static final tmd D;
    public static final tmd D0;
    public static final tmd E;
    public static final tmd E0;
    public static final tmd F;
    public static final tmd F0;
    public static final tmd G;
    public static final tmd G0;
    public static final tmd H;
    public static final tmd H0;
    public static final tmd I;
    public static final tmd I0;
    public static final tmd J;
    public static final tmd J0;
    public static final tmd K;
    public static final tmd K0;
    public static final tmd L;
    public static final tmd L0;
    public static final tmd M;
    public static final tmd M0;
    public static final tmd N;
    public static final tmd N0;
    public static final tmd O;
    public static final tmd O0;
    public static final tmd P;
    public static final tmd P0;
    public static final tmd Q;
    public static final tmd Q0;
    public static final tmd R;
    public static final tmd R0;
    public static final tmd S;
    public static final tmd S0;
    public static final tmd T;
    public static final tmd T0;
    public static final tmd U;
    public static final tmd U0;
    public static final tmd V;
    public static final tmd V0;
    public static final tmd W;
    public static final tmd W0;
    public static final tmd X;
    public static final tmd X0;
    public static final tmd Y;
    public static final tmd Y0;
    public static final tmd Z;
    public static final tmd Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final tmd a0;
    public static final tmd a1;
    public static final tmd b;
    public static final tmd b0;
    public static final tmd b1;
    public static final tmd c;
    public static final tmd c0;
    public static final tmd c1;
    public static final tmd d;
    public static final tmd d0;
    public static final tmd d1;
    public static final tmd e;
    public static final tmd e0;
    public static final tmd e1;
    public static final tmd f;
    public static final tmd f0;
    public static final tmd f1;
    public static final tmd g;
    public static final tmd g0;
    public static final tmd g1;
    public static final tmd h;
    public static final tmd h0;
    public static final tmd h1;
    public static final tmd i;
    public static final tmd i0;
    public static final tmd i1;
    public static final tmd j;
    public static final tmd j0;
    public static final tmd j1;
    public static final tmd k;
    public static final tmd k0;
    public static final tmd l;
    public static final tmd l0;
    public static final tmd m;
    public static final tmd m0;
    public static final tmd n;
    public static final tmd n0;
    public static final tmd o;
    public static final tmd o0;
    public static final tmd p;
    public static final tmd p0;
    public static final tmd q;
    public static final tmd q0;
    public static final tmd r;
    public static final tmd r0;
    public static final tmd s;
    public static final tmd s0;
    public static final tmd t;
    public static final tmd t0;
    public static final tmd u;
    public static final tmd u0;
    public static final tmd v;
    public static final tmd v0;
    public static final tmd w;
    public static final tmd w0;
    public static final tmd x;
    public static final tmd x0;
    public static final tmd y;
    public static final tmd y0;
    public static final tmd z;
    public static final tmd z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, y3a.G, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, yja.c, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, o7a.c, false);
        e = a("measurement.config.cache_time", 86400000L, o7a.d, false);
        f = a("measurement.config.url_scheme", "https", o7a.e, false);
        g = a("measurement.config.url_authority", "app-measurement.com", m8a.f, false);
        h = a("measurement.upload.max_bundles", 100, o7a.B, false);
        Integer valueOf = Integer.valueOf((int) Parser.ARGC_LIMIT);
        i = a("measurement.upload.max_batch_size", valueOf, o7a.C, false);
        j = a("measurement.upload.max_bundle_size", valueOf, w5a.D, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, kca.D, false);
        l = a("measurement.upload.max_events_per_day", 100000, kma.G, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, m8a.c, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, iba.d, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, kca.c, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, fda.c, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, kfa.c, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", kma.d, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", y3a.c, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", b4a.d, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", s5a.d, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, w5a.c, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, m8a.d, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, kca.d, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, fda.d, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, kfa.d, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, yja.d, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, kma.e, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, y3a.d, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, b4a.e, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, s5a.e, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, w5a.d, false);
        G = a("measurement.upload.backoff_period", 43200000L, m8a.e, false);
        a("measurement.upload.window_interval", 3600000L, iba.e, false);
        H = a("measurement.upload.interval", 3600000L, kca.e, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, fda.e, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, kfa.e, false);
        K = a("measurement.upload.minimum_delay", 500L, yja.e, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, kma.f, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, y3a.e, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, b4a.f, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, w5a.e, false);
        P = a("measurement.upload.retry_time", 1800000L, iba.f, false);
        Q = a("measurement.upload.retry_count", 6, fda.f, false);
        R = a("measurement.upload.max_queue_time", 518400000L, kfa.f, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, yja.f, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, kma.B, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf((int) Context.VERSION_ES6), y3a.f, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, b4a.B, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, s5a.f, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, w5a.f, false);
        b0 = a("measurement.test.test_string_flag", "---", o7a.f, false);
        c0 = a("measurement.test.test_long_flag", -1L, iba.B, false);
        a("measurement.test.test_cached_long_flag", -1L, kca.f, true);
        d0 = a("measurement.test.test_int_flag", -2, fda.B, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), kfa.B, false);
        a("measurement.experiment.max_ids", 50, yja.B, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, kma.C, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, y3a.B, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, b4a.C, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, s5a.B, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, w5a.B, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, m8a.B, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, iba.C, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", fda.C, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", kfa.C, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", yja.C, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, kma.D, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", y3a.C, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", b4a.D, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", s5a.C, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", w5a.C, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, m8a.C, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, iba.D, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, kca.B, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, fda.D, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, kfa.D, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, yja.D, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, kma.E, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, y3a.D, false);
        a("measurement.config.default_flag_values", bool2, b4a.E, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, s5a.D, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, o7a.D, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, m8a.D, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, iba.E, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, kca.C, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, fda.E, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, kfa.E, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, y3a.E, false);
        K0 = a("measurement.service.store_null_safelist", bool2, s5a.E, false);
        L0 = a("measurement.service.store_safelist", bool2, w5a.E, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, m8a.E, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, fda.F, true);
        O0 = a("measurement.rb.attribution.service", bool2, yja.E, true);
        P0 = a("measurement.rb.attribution.client2", bool2, kma.F, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, y3a.F, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, s5a.F, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, m8a.F, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, w5a.F, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, o7a.E, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, iba.F, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, fda.G, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, kfa.F, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, iba.c, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, m8a.b, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, kfa.b, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, s5a.G, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, b4a.F, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", kma.c, false);
        c1 = a("measurement.edpb.service", bool, fda.b, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", y3a.b, false);
        e1 = a("measurement.robust_time_source_2", bool, o7a.F, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, w5a.G, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", b4a.c, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", s5a.c, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", o7a.b, false);
        j1 = a("measurement.diagnostics.enabled", bool, kca.b, false);
    }

    public static tmd a(String str, Object obj, wcd wcdVar, boolean z2) {
        tmd tmdVar = new tmd(str, obj, wcdVar);
        if (z2) {
            a.add(tmdVar);
        }
        return tmdVar;
    }
}
