package defpackage;
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: wib  reason: default package */
/* loaded from: classes.dex */
public abstract class wib {
    public static final igb A0;
    public static final bhb B;
    public static final kgb B0;
    public static final vhb C;
    public static final ugb C0;
    public static final bib D;
    public static final lhb D0;
    public static final shb E;
    public static final mhb E0;
    public static final vib F;
    public static final jgb F0;
    public static final phb G;
    public static final wgb G0;
    public static final uib H;
    public static final mgb H0;
    public static final aib I;
    public static final vgb I0;
    public static final uhb J;
    public static final nhb J0;
    public static final thb K;
    public static final ohb K0;
    public static final yhb L;
    public static final lgb L0;
    public static final xhb M;
    public static final ygb M0;
    public static final whb N;
    public static final zgb N0;
    public static final sib O;
    public static final /* synthetic */ wib[] O0;
    public static final jib P;
    public static final iib Q;
    public static final kib R;
    public static final lib S;
    public static final mib T;
    public static final nib U;
    public static final oib V;
    public static final rib W;
    public static final qib X;
    public static final pib Y;
    public static final dib Z;
    public static final kma a;
    public static final eib a0;
    public static final char[] b;
    public static final fib b0;
    public static final char[] c;
    public static final gib c0;
    public static final ihb d;
    public static final hib d0;
    public static final ahb e;
    public static final cib e0;
    public static final zhb f;
    public static final rgb f0;
    public static final ngb g0;
    public static final ggb h0;
    public static final sgb i0;
    public static final ogb j0;
    public static final pgb k0;
    public static final qgb l0;
    public static final hgb m0;
    public static final tib n0;
    public static final xgb o0;
    public static final qhb p0;
    public static final rhb q0;
    public static final ghb r0;
    public static final hhb s0;
    public static final chb t0;
    public static final fhb u0;
    public static final dhb v0;
    public static final ehb w0;
    public static final jhb x0;
    public static final tgb y0;
    public static final khb z0;

    static {
        ihb ihbVar = new ihb();
        d = ihbVar;
        ahb ahbVar = new ahb();
        e = ahbVar;
        zhb zhbVar = new zhb();
        f = zhbVar;
        bhb bhbVar = new bhb();
        B = bhbVar;
        vhb vhbVar = new vhb();
        C = vhbVar;
        bib bibVar = new bib();
        D = bibVar;
        shb shbVar = new shb();
        E = shbVar;
        vib vibVar = new vib();
        F = vibVar;
        phb phbVar = new phb();
        G = phbVar;
        uib uibVar = new uib();
        H = uibVar;
        aib aibVar = new aib();
        I = aibVar;
        uhb uhbVar = new uhb();
        J = uhbVar;
        thb thbVar = new thb();
        K = thbVar;
        yhb yhbVar = new yhb();
        L = yhbVar;
        xhb xhbVar = new xhb();
        M = xhbVar;
        whb whbVar = new whb();
        N = whbVar;
        sib sibVar = new sib();
        O = sibVar;
        jib jibVar = new jib();
        P = jibVar;
        iib iibVar = new iib();
        Q = iibVar;
        kib kibVar = new kib();
        R = kibVar;
        lib libVar = new lib();
        S = libVar;
        mib mibVar = new mib();
        T = mibVar;
        nib nibVar = new nib();
        U = nibVar;
        oib oibVar = new oib();
        V = oibVar;
        rib ribVar = new rib();
        W = ribVar;
        qib qibVar = new qib();
        X = qibVar;
        pib pibVar = new pib();
        Y = pibVar;
        dib dibVar = new dib();
        Z = dibVar;
        eib eibVar = new eib();
        a0 = eibVar;
        fib fibVar = new fib();
        b0 = fibVar;
        gib gibVar = new gib();
        c0 = gibVar;
        hib hibVar = new hib();
        d0 = hibVar;
        cib cibVar = new cib();
        e0 = cibVar;
        rgb rgbVar = new rgb();
        f0 = rgbVar;
        ngb ngbVar = new ngb();
        g0 = ngbVar;
        ggb ggbVar = new ggb();
        h0 = ggbVar;
        sgb sgbVar = new sgb();
        i0 = sgbVar;
        ogb ogbVar = new ogb();
        j0 = ogbVar;
        pgb pgbVar = new pgb();
        k0 = pgbVar;
        qgb qgbVar = new qgb();
        l0 = qgbVar;
        hgb hgbVar = new hgb();
        m0 = hgbVar;
        tib tibVar = new tib();
        n0 = tibVar;
        xgb xgbVar = new xgb();
        o0 = xgbVar;
        qhb qhbVar = new qhb();
        p0 = qhbVar;
        rhb rhbVar = new rhb();
        q0 = rhbVar;
        ghb ghbVar = new ghb();
        r0 = ghbVar;
        hhb hhbVar = new hhb();
        s0 = hhbVar;
        chb chbVar = new chb();
        t0 = chbVar;
        fhb fhbVar = new fhb();
        u0 = fhbVar;
        dhb dhbVar = new dhb();
        v0 = dhbVar;
        ehb ehbVar = new ehb();
        w0 = ehbVar;
        jhb jhbVar = new jhb();
        x0 = jhbVar;
        tgb tgbVar = new tgb();
        y0 = tgbVar;
        khb khbVar = new khb();
        z0 = khbVar;
        igb igbVar = new igb();
        A0 = igbVar;
        kgb kgbVar = new kgb();
        B0 = kgbVar;
        ugb ugbVar = new ugb();
        C0 = ugbVar;
        lhb lhbVar = new lhb();
        D0 = lhbVar;
        mhb mhbVar = new mhb();
        E0 = mhbVar;
        jgb jgbVar = new jgb();
        F0 = jgbVar;
        wgb wgbVar = new wgb();
        G0 = wgbVar;
        mgb mgbVar = new mgb();
        H0 = mgbVar;
        vgb vgbVar = new vgb();
        I0 = vgbVar;
        nhb nhbVar = new nhb();
        J0 = nhbVar;
        ohb ohbVar = new ohb();
        K0 = ohbVar;
        lgb lgbVar = new lgb();
        L0 = lgbVar;
        ygb ygbVar = new ygb();
        M0 = ygbVar;
        zgb zgbVar = new zgb();
        N0 = zgbVar;
        O0 = new wib[]{ihbVar, ahbVar, zhbVar, bhbVar, vhbVar, bibVar, shbVar, vibVar, phbVar, uibVar, aibVar, uhbVar, thbVar, yhbVar, xhbVar, whbVar, sibVar, jibVar, iibVar, kibVar, libVar, mibVar, nibVar, oibVar, ribVar, qibVar, pibVar, dibVar, eibVar, fibVar, gibVar, hibVar, cibVar, rgbVar, ngbVar, ggbVar, sgbVar, ogbVar, pgbVar, qgbVar, hgbVar, tibVar, xgbVar, qhbVar, rhbVar, ghbVar, hhbVar, chbVar, fhbVar, dhbVar, ehbVar, jhbVar, tgbVar, khbVar, igbVar, kgbVar, ugbVar, lhbVar, mhbVar, jgbVar, wgbVar, mgbVar, vgbVar, nhbVar, ohbVar, lgbVar, ygbVar, zgbVar};
        a = new kma(1);
        b = new char[]{'\t', '\n', '\f', '\r', ' ', '\"', '\'', '/', '<', '=', '>', '?'};
        c = new char[]{0, '\t', '\n', '\f', '\r', ' ', '\"', '&', '\'', '<', '=', '>', '`'};
    }

    public static wib valueOf(String str) {
        return (wib) Enum.valueOf(wib.class, str);
    }

    public static wib[] values() {
        return (wib[]) O0.clone();
    }

    public abstract void a(fgb fgbVar, h71 h71Var);
}
