package defpackage;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: wub  reason: default package */
/* loaded from: classes.dex */
public abstract class wub {
    public static final long A;
    public static final long A0;
    public static final wl4 A1;
    public static final long B;
    public static final qf4 B0;
    public static final long B1;
    public static final long C;
    public static final wl4 C0;
    public static final long C1;
    public static final qf4 D;
    public static final long D0;
    public static final long D1;
    public static final wl4 E;
    public static final long E0;
    public static final qf4 E1;
    public static final long F;
    public static final long F0;
    public static final wl4 F1;
    public static final long G;
    public static final qf4 G0;
    public static final long G1;
    public static final long H;
    public static final wl4 H0;
    public static final long H1;
    public static final qf4 I;
    public static final long I0;
    public static final long I1;
    public static final wl4 J;
    public static final long J0;
    public static final qf4 J1;
    public static final long K;
    public static final long K0;
    public static final wl4 K1;
    public static final long L;
    public static final qf4 L0;
    public static final long L1;
    public static final long M;
    public static final wl4 M0;
    public static final long M1;
    public static final qf4 N;
    public static final long N0;
    public static final long N1;
    public static final wl4 O;
    public static final long O0;
    public static final qf4 O1;
    public static final long P;
    public static final long P0;
    public static final wl4 P1;
    public static final long Q;
    public static final qf4 Q0;
    public static final long Q1;
    public static final long R;
    public static final wl4 R0;
    public static final long R1;
    public static final qf4 S;
    public static final long S0;
    public static final long S1;
    public static final wl4 T;
    public static final long T0;
    public static final qf4 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final qf4 V0;
    public static final long W;
    public static final wl4 W0;
    public static final qf4 X;
    public static final long X0;
    public static final wl4 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final wl4 a;
    public static final long a0;
    public static final qf4 a1;
    public static final long b;
    public static final long b0;
    public static final wl4 b1;
    public static final long c;
    public static final qf4 c0;
    public static final long c1;
    public static final long d;
    public static final wl4 d0;
    public static final long d1;
    public static final qf4 e;
    public static final long e0;
    public static final long e1;
    public static final wl4 f;
    public static final long f0;
    public static final qf4 f1;
    public static final long g;
    public static final long g0;
    public static final wl4 g1;
    public static final long h;
    public static final qf4 h0;
    public static final long h1;
    public static final long i;
    public static final wl4 i0;
    public static final long i1;
    public static final qf4 j;
    public static final long j0;
    public static final long j1;
    public static final wl4 k;
    public static final long k0;
    public static final qf4 k1;
    public static final long l;
    public static final long l0;
    public static final wl4 l1;
    public static final long m;
    public static final qf4 m0;
    public static final long m1;
    public static final long n;
    public static final wl4 n0;
    public static final long n1;
    public static final qf4 o;
    public static final long o0;
    public static final long o1;
    public static final wl4 p;
    public static final long p0;
    public static final qf4 p1;
    public static final long q;
    public static final long q0;
    public static final wl4 q1;
    public static final long r;
    public static final qf4 r0;
    public static final long r1;
    public static final long s;
    public static final wl4 s0;
    public static final long s1;
    public static final qf4 t;
    public static final long t0;
    public static final long t1;
    public static final wl4 u;
    public static final long u0;
    public static final qf4 u1;
    public static final long v;
    public static final long v0;
    public static final wl4 v1;
    public static final long w;
    public static final qf4 w0;
    public static final long w1;
    public static final long x;
    public static final wl4 x0;
    public static final long x1;
    public static final qf4 y;
    public static final long y0;
    public static final long y1;
    public static final wl4 z;
    public static final long z0;
    public static final qf4 z1;

    static {
        qf4 qf4Var = lvb.a;
        wl4 wl4Var = sd4.b;
        a = wl4Var;
        b = cbd.l(24.0d);
        c = cbd.m(16);
        d = cbd.l(0.5d);
        qf4 qf4Var2 = lvb.c;
        e = qf4Var2;
        f = wl4Var;
        g = cbd.l(20.0d);
        h = cbd.m(14);
        i = cbd.l(0.2d);
        j = qf4Var2;
        k = wl4Var;
        l = cbd.l(16.0d);
        m = cbd.m(12);
        n = cbd.l(0.4d);
        o = qf4Var2;
        p = wl4Var;
        q = cbd.l(64.0d);
        r = cbd.m(57);
        long l2 = cbd.l(0.2d);
        cbd.d(l2);
        s = cbd.q(-w7b.c(l2), l2 & 1095216660480L);
        t = qf4Var2;
        u = wl4Var;
        v = cbd.l(52.0d);
        w = cbd.m(45);
        x = cbd.l(0.0d);
        y = qf4Var2;
        z = wl4Var;
        A = cbd.l(44.0d);
        B = cbd.m(36);
        C = cbd.l(0.0d);
        D = qf4Var2;
        E = wl4Var;
        F = cbd.l(40.0d);
        G = cbd.m(32);
        H = cbd.l(0.0d);
        I = qf4Var2;
        J = wl4Var;
        K = cbd.l(36.0d);
        L = cbd.m(28);
        M = cbd.l(0.0d);
        N = qf4Var2;
        O = wl4Var;
        P = cbd.l(32.0d);
        Q = cbd.m(24);
        R = cbd.l(0.0d);
        S = qf4Var2;
        T = wl4Var;
        U = cbd.l(20.0d);
        V = cbd.m(14);
        W = cbd.l(0.1d);
        qf4 qf4Var3 = lvb.b;
        X = qf4Var3;
        Y = wl4Var;
        Z = cbd.l(16.0d);
        a0 = cbd.m(12);
        b0 = cbd.l(0.5d);
        c0 = qf4Var3;
        d0 = wl4Var;
        e0 = cbd.l(16.0d);
        f0 = cbd.m(11);
        g0 = cbd.l(0.5d);
        h0 = qf4Var3;
        i0 = wl4Var;
        j0 = cbd.l(28.0d);
        k0 = cbd.m(22);
        l0 = cbd.l(0.0d);
        m0 = qf4Var2;
        n0 = wl4Var;
        o0 = cbd.l(24.0d);
        p0 = cbd.m(16);
        q0 = cbd.l(0.2d);
        r0 = qf4Var3;
        s0 = wl4Var;
        t0 = cbd.l(20.0d);
        u0 = cbd.m(14);
        v0 = cbd.l(0.1d);
        w0 = qf4Var3;
        x0 = wl4Var;
        y0 = cbd.l(24.0d);
        z0 = cbd.m(16);
        A0 = cbd.l(0.15d);
        B0 = qf4Var3;
        C0 = wl4Var;
        D0 = cbd.l(20.0d);
        E0 = cbd.m(14);
        F0 = cbd.l(0.25d);
        G0 = qf4Var3;
        H0 = wl4Var;
        I0 = cbd.l(16.0d);
        J0 = cbd.m(12);
        K0 = cbd.l(0.4d);
        L0 = qf4Var3;
        M0 = wl4Var;
        N0 = cbd.l(64.0d);
        O0 = cbd.m(57);
        P0 = cbd.m(0);
        Q0 = qf4Var3;
        R0 = wl4Var;
        S0 = cbd.l(52.0d);
        T0 = cbd.m(45);
        U0 = cbd.m(0);
        V0 = qf4Var3;
        W0 = wl4Var;
        X0 = cbd.l(44.0d);
        Y0 = cbd.m(36);
        Z0 = cbd.m(0);
        a1 = qf4Var3;
        b1 = wl4Var;
        c1 = cbd.l(40.0d);
        d1 = cbd.m(32);
        e1 = cbd.m(0);
        f1 = qf4Var3;
        g1 = wl4Var;
        h1 = cbd.l(36.0d);
        i1 = cbd.m(28);
        j1 = cbd.m(0);
        k1 = qf4Var3;
        l1 = wl4Var;
        m1 = cbd.l(32.0d);
        n1 = cbd.m(24);
        o1 = cbd.m(0);
        p1 = qf4Var3;
        q1 = wl4Var;
        r1 = cbd.l(20.0d);
        s1 = cbd.m(14);
        t1 = cbd.l(0.1d);
        qf4 qf4Var4 = lvb.a;
        u1 = qf4Var4;
        v1 = wl4Var;
        w1 = cbd.l(16.0d);
        x1 = cbd.m(12);
        y1 = cbd.l(0.5d);
        z1 = qf4Var4;
        A1 = wl4Var;
        B1 = cbd.l(16.0d);
        C1 = cbd.m(11);
        D1 = cbd.l(0.5d);
        E1 = qf4Var4;
        F1 = wl4Var;
        G1 = cbd.l(28.0d);
        H1 = cbd.m(22);
        I1 = cbd.m(0);
        J1 = qf4Var3;
        K1 = wl4Var;
        L1 = cbd.l(24.0d);
        M1 = cbd.m(16);
        N1 = cbd.l(0.15d);
        O1 = qf4Var4;
        P1 = wl4Var;
        Q1 = cbd.l(20.0d);
        R1 = cbd.m(14);
        S1 = cbd.l(0.1d);
        T1 = qf4Var4;
    }
}
