package defpackage;

import java.security.GeneralSecurityException;
import java.util.Collections;
import java.util.HashMap;
/* compiled from: r8-map-id-4d6d8fcf5aedffa2274f080361e1b4e46b63437b827bc423e1864d8796e13b50 */
/* renamed from: zxd  reason: default package */
/* loaded from: classes.dex */
public abstract class zxd {
    static {
        int i = uge.a;
        try {
            a();
        } catch (GeneralSecurityException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    public static void a() {
        f4e f4eVar = f4e.b;
        f4eVar.a(jhd.f);
        f4eVar.b(jhd.g);
        f4eVar.a(jhd.h);
        f4eVar.b(jhd.i);
        ygd.a();
        mvd.a();
        if (hud.a()) {
            return;
        }
        c5e c5eVar = iwd.a;
        if (jlb.d(1)) {
            s4e s4eVar = izd.a;
            e4e e4eVar = e4e.b;
            e4eVar.h(izd.a);
            e4eVar.g(izd.b);
            e4eVar.f(izd.c);
            e4eVar.e(izd.d);
            e4eVar.f(izd.e);
            e4eVar.e(izd.f);
            z3e z3eVar = z3e.b;
            HashMap hashMap = new HashMap();
            av b = rwd.b();
            nwd nwdVar = nwd.b;
            b.a = nwdVar;
            mwd mwdVar = mwd.d;
            b.b = mwdVar;
            pwd pwdVar = pwd.c;
            b.c = pwdVar;
            owd owdVar = owd.b;
            b.e = owdVar;
            a6c b2 = ijd.b();
            b2.p();
            b2.A(16);
            b2.E();
            hjd hjdVar = hjd.e;
            b2.e = hjdVar;
            b.B(b2.l());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM", b.z());
            av b3 = rwd.b();
            b3.a = nwdVar;
            b3.b = mwdVar;
            b3.c = pwdVar;
            owd owdVar2 = owd.d;
            b3.e = owdVar2;
            a6c b4 = ijd.b();
            b4.p();
            b4.A(16);
            b4.E();
            b4.e = hjdVar;
            b3.B(b4.l());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_RAW", b3.z());
            av b5 = rwd.b();
            b5.a = nwdVar;
            b5.b = mwdVar;
            pwd pwdVar2 = pwd.b;
            b5.c = pwdVar2;
            b5.e = owdVar;
            a6c b6 = ijd.b();
            b6.p();
            b6.A(16);
            b6.E();
            b6.e = hjdVar;
            b5.B(b6.l());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM", b5.z());
            av b7 = rwd.b();
            b7.a = nwdVar;
            b7.b = mwdVar;
            b7.c = pwdVar2;
            b7.e = owdVar2;
            a6c b8 = ijd.b();
            b8.p();
            b8.A(16);
            b8.E();
            b8.e = hjdVar;
            b7.B(b8.l());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM_RAW", b7.z());
            av b9 = rwd.b();
            b9.a = nwdVar;
            b9.b = mwdVar;
            b9.c = pwdVar2;
            b9.e = owdVar2;
            a6c b10 = ijd.b();
            b10.p();
            b10.A(16);
            b10.E();
            b10.e = hjdVar;
            b9.B(b10.l());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_COMPRESSED_WITHOUT_PREFIX", b9.z());
            av b11 = rwd.b();
            b11.a = nwdVar;
            b11.b = mwdVar;
            b11.c = pwdVar;
            b11.e = owdVar;
            av b12 = did.b();
            b12.A(16);
            b12.C(32);
            b12.I(16);
            b12.F(16);
            bid bidVar = bid.e;
            b12.e = bidVar;
            aid aidVar = aid.e;
            b12.f = aidVar;
            b11.B(b12.y());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", b11.z());
            av b13 = rwd.b();
            b13.a = nwdVar;
            b13.b = mwdVar;
            b13.c = pwdVar;
            b13.e = owdVar2;
            av b14 = did.b();
            b14.A(16);
            b14.C(32);
            b14.I(16);
            b14.F(16);
            b14.e = bidVar;
            b14.f = aidVar;
            b13.B(b14.y());
            hashMap.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", b13.z());
            av b15 = rwd.b();
            b15.a = nwdVar;
            b15.b = mwdVar;
            b15.c = pwdVar2;
            b15.e = owdVar;
            av b16 = did.b();
            b16.A(16);
            b16.C(32);
            b16.I(16);
            b16.F(16);
            b16.e = bidVar;
            b16.f = aidVar;
            b15.B(b16.y());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", b15.z());
            av b17 = rwd.b();
            b17.a = nwdVar;
            b17.b = mwdVar;
            b17.c = pwdVar2;
            b17.e = owdVar2;
            av b18 = did.b();
            b18.A(16);
            b18.C(32);
            b18.I(16);
            b18.F(16);
            b18.e = bidVar;
            b18.f = aidVar;
            b17.B(b18.y());
            hashMap.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", b17.z());
            z3eVar.b(Collections.unmodifiableMap(hashMap));
            f4eVar.b(iwd.a);
            f4eVar.b(iwd.b);
            r3e r3eVar = r3e.b;
            r3eVar.b(iwd.e, rwd.class);
            c2e c2eVar = c2e.d;
            c2eVar.c(iwd.c, true);
            c2eVar.c(iwd.d, false);
            c5e c5eVar2 = l0e.a;
            if (jlb.d(1)) {
                e4eVar.h(lxd.a);
                e4eVar.g(lxd.b);
                e4eVar.f(lxd.c);
                e4eVar.e(lxd.d);
                e4eVar.f(lxd.e);
                e4eVar.e(lxd.f);
                HashMap hashMap2 = new HashMap();
                a6c b19 = exd.b();
                axd axdVar = axd.b;
                b19.e = axdVar;
                bxd bxdVar = bxd.B;
                b19.b = bxdVar;
                zwd zwdVar = zwd.d;
                b19.c = zwdVar;
                ywd ywdVar = ywd.d;
                b19.d = ywdVar;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", b19.m());
                a6c b20 = exd.b();
                axd axdVar2 = axd.d;
                b20.e = axdVar2;
                b20.b = bxdVar;
                b20.c = zwdVar;
                b20.d = ywdVar;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", b20.m());
                a6c b21 = exd.b();
                b21.e = axdVar;
                b21.b = bxdVar;
                b21.c = zwdVar;
                ywd ywdVar2 = ywd.e;
                b21.d = ywdVar2;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", b21.m());
                a6c b22 = exd.b();
                b22.e = axdVar2;
                b22.b = bxdVar;
                b22.c = zwdVar;
                b22.d = ywdVar2;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", b22.m());
                a6c b23 = exd.b();
                b23.e = axdVar;
                b23.b = bxdVar;
                b23.c = zwdVar;
                ywd ywdVar3 = ywd.f;
                b23.d = ywdVar3;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305", b23.m());
                a6c b24 = exd.b();
                b24.e = axdVar2;
                b24.b = bxdVar;
                b24.c = zwdVar;
                b24.d = ywdVar3;
                hashMap2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305_RAW", b24.m());
                a6c b25 = exd.b();
                b25.e = axdVar;
                bxd bxdVar2 = bxd.d;
                b25.b = bxdVar2;
                b25.c = zwdVar;
                b25.d = ywdVar;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", b25.m());
                a6c b26 = exd.b();
                b26.e = axdVar2;
                b26.b = bxdVar2;
                b26.c = zwdVar;
                b26.d = ywdVar;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", b26.m());
                a6c b27 = exd.b();
                b27.e = axdVar;
                b27.b = bxdVar2;
                b27.c = zwdVar;
                b27.d = ywdVar2;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", b27.m());
                a6c b28 = exd.b();
                b28.e = axdVar2;
                b28.b = bxdVar2;
                b28.c = zwdVar;
                b28.d = ywdVar2;
                hashMap2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", b28.m());
                a6c b29 = exd.b();
                b29.e = axdVar;
                bxd bxdVar3 = bxd.e;
                b29.b = bxdVar3;
                zwd zwdVar2 = zwd.e;
                b29.c = zwdVar2;
                b29.d = ywdVar;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM", b29.m());
                a6c b30 = exd.b();
                b30.e = axdVar2;
                b30.b = bxdVar3;
                b30.c = zwdVar2;
                b30.d = ywdVar;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM_RAW", b30.m());
                a6c b31 = exd.b();
                b31.e = axdVar;
                b31.b = bxdVar3;
                b31.c = zwdVar2;
                b31.d = ywdVar2;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM", b31.m());
                a6c b32 = exd.b();
                b32.e = axdVar2;
                b32.b = bxdVar3;
                b32.c = zwdVar2;
                b32.d = ywdVar2;
                hashMap2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM_RAW", b32.m());
                a6c b33 = exd.b();
                b33.e = axdVar;
                bxd bxdVar4 = bxd.f;
                b33.b = bxdVar4;
                zwd zwdVar3 = zwd.f;
                b33.c = zwdVar3;
                b33.d = ywdVar;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM", b33.m());
                a6c b34 = exd.b();
                b34.e = axdVar2;
                b34.b = bxdVar4;
                b34.c = zwdVar3;
                b34.d = ywdVar;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM_RAW", b34.m());
                a6c b35 = exd.b();
                b35.e = axdVar;
                b35.b = bxdVar4;
                b35.c = zwdVar3;
                b35.d = ywdVar2;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM", b35.m());
                a6c b36 = exd.b();
                b36.e = axdVar2;
                b36.b = bxdVar4;
                b36.c = zwdVar3;
                b36.d = ywdVar2;
                hashMap2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM_RAW", b36.m());
                z3eVar.b(Collections.unmodifiableMap(hashMap2));
                f4eVar.b(l0e.a);
                f4eVar.b(l0e.b);
                r3eVar.b(l0e.e, exd.class);
                c2eVar.c(l0e.c, true);
                c2eVar.c(l0e.d, false);
                return;
            }
            mnc.g("Registering HPKE Hybrid Encryption is not supported in FIPS mode");
            return;
        }
        mnc.g("Registering ECIES Hybrid Encryption is not supported in FIPS mode");
    }
}
